bkup: 'if elif else' -> 'case' in main()

diff --git a/.local/bin/bkup b/.local/bin/bkup
--- a/.local/bin/bkup
+++ b/.local/bin/bkup
@@ -79,17 +79,21 @@ read -r continue
 main() {
 must_be_root
 prompt
-if [ "${continue}" = "n" ]; then
-  sec_print "Goodbye."
-elif [ "${continue}" = "y" ]; then
-  /bin/mkdir -p "/mnt/${date}" || err "Unable to create backup directory."
-  sec_print "Dumping filesystems..."
-  bkup || err "Backup failed."
-  /sbin/umount /mnt || err "Unable to unmount drive"
-  /sbin/shutdown -p now
-else
-  err "You must answer with 'y' or 'n'."
-fi
+case "${continue}" in
+  n)
+    sec_print "Goodbye."
+    ;;
+  y)
+    /bin/mkdir -p "/mnt/${date}" || err "Unable to create backup directory."
+    sec_print "Dumping filesystems..."
+    bkup || err "Backup failed."
+    /sbin/umount /mnt || err "Unable to unmount drive"
+    /sbin/shutdown -p now
+    ;;
+  *)
+    err "You must answer with 'y' or 'n'."
+    ;;
+esac
 }
 
 main
