indentation level 2 -> 4. nvim config changed accordingly. style inconsistencies fixed while here.

diff --git a/.local/bin/check-batt b/.local/bin/check-batt
--- a/.local/bin/check-batt
+++ b/.local/bin/check-batt
@@ -15,18 +15,18 @@
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -43,8 +43,8 @@ EOF
 
 # if battery is missing, exit.
 case "$(apm -b)" in
-  4)   err "Battery status is 'absent.'"  ;;
-  255) err "Battery status is 'unknown.'" ;;
+    4)   err "Battery status is 'absent.'"  ;;
+    255) err "Battery status is 'unknown.'" ;;
 esac
 
 
@@ -52,12 +52,12 @@ BATT_PERCENT="$(apm -l)"
 readonly BATT_PERCENT
 
 if [ "${BATT_PERCENT}" -lt 20 ]; then
-  # exporting ${DISPLAY} is needed for cron(8) jobs.
-  [ -z "${DISPLAY}" ] && export DISPLAY=:0
+    # exporting ${DISPLAY} is needed for cron(8) jobs.
+    [ -z "${DISPLAY}" ] && export DISPLAY=:0
 
-  notify-send -- "🔋 Your device is at ${BATT_PERCENT}%!"
+    notify-send -- "🔋 Your device is at ${BATT_PERCENT}%!"
 
 else
-  exit 0
+    exit 0
 
 fi
diff --git a/.local/bin/check-elemweb b/.local/bin/check-elemweb
--- a/.local/bin/check-elemweb
+++ b/.local/bin/check-elemweb
@@ -17,17 +17,17 @@
 
 
 make_release_url() {
-  printf "https://${GH_API}/repos/%s/%s/releases/latest\n" "$1" "$2"
+    printf "https://${GH_API}/repos/%s/%s/releases/latest\n" "$1" "$2"
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -44,8 +44,8 @@ EOF
 
 
 VERSION="$(ftp -VMno - "$(make_release_url vector-im element-web)" \
-  | jq -er '.name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+-rc") | not)')" \
-  || exit 1
+    | jq -er '.name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+-rc") | not)')" \
+    || exit 1
 
 
 readonly ELEMENT_WEB_UI_DIR='/var/www/htdocs/element-web'
@@ -57,9 +57,9 @@ perl -e "exit !(${VERSION} gt ${CURRENT_VERSION})" || exit 1
 
 
 if "${INSTALL_SCRIPT}" "${VERSION}"; then
-  printf '%s: element-web updated to %s\n' "${0##*/}" "${VERSION}" >&2
+    printf '%s: element-web updated to %s\n' "${0##*/}" "${VERSION}" >&2
 
 else
-  printf '%s: failed to update element-web to %s\n' "${0##*/}" "${VERSION}" >&2
+    printf '%s: failed to update element-web to %s\n' "${0##*/}" "${VERSION}" >&2
 
 fi
diff --git a/.local/bin/clear_clip b/.local/bin/clear_clip
--- a/.local/bin/clear_clip
+++ b/.local/bin/clear_clip
@@ -17,18 +17,18 @@
 set -e
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -40,6 +40,6 @@ EOF
 xclip -selection clipboard -i /dev/null || err 'Unable to clear the clipboard.'
 
 case "$1" in
-  'notify') notify-send '📋 Cleared the clipboard.'             ;;
-  *)        # undefined positional parameters should do nothing ;;
+    'notify') notify-send '📋 Cleared the clipboard.'             ;;
+    *)        # undefined positional parameters should do nothing ;;
 esac
diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -9,46 +9,46 @@
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 menu() {
-  dmenu -i -l 20               \
-  -fn 'mono-12'                \
-  -fn 'Symbola-12'             \
-  -nb "${background:-#040516}" \
-  -nf "${color3:-#9974e7}"     \
-  -sb "${background:-#040516}" \
-  -sf "${foreground:-#e0cef3}"
+    dmenu -i -l 20                   \
+        -fn 'mono-12'                \
+        -fn 'Symbola-12'             \
+        -nb "${background:-#040516}" \
+        -nf "${color3:-#9974e7}"     \
+        -sb "${background:-#040516}" \
+        -sf "${foreground:-#e0cef3}"
 }
 
 
 import_colors_sh() {
-  readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+    readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
 
-  if ! [ -r "${COLORS_SH}" ]; then
-    echo "${COLORS_SH} is not readable." >&2
+    if ! [ -r "${COLORS_SH}" ]; then
+        echo "${COLORS_SH} is not readable." >&2
 
-  elif ! [ -f "${COLORS_SH}" ]; then
-    echo "${COLORS_SH} is not a file." >&2
+    elif ! [ -f "${COLORS_SH}" ]; then
+        echo "${COLORS_SH} is not a file." >&2
 
-  # passed sanity checks, so source the file
-  else
-    . "${COLORS_SH}"
+    # passed sanity checks, so source the file
+    else
+        . "${COLORS_SH}"
 
-  fi
+    fi
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -84,9 +84,9 @@ grep -q -- "^${EMOJI}" "${EMOJI_FILE}" || err "Emoji not found in ${EMOJI_FILE}.
 # also important to not send a newline to xclip(1), otherwise pasting
 # from the clipboard in certain messengers will send the message.
 if printf '%s' "${EMOJI}" | xclip -selection clipboard; then
-  notify-send -- "${EMOJI} copied to clipboard."
+    notify-send -- "${EMOJI} copied to clipboard."
 
 else
-  err 'Unable to grab emoji with xclip(1).'
+    err 'Unable to grab emoji with xclip(1).'
 
 fi
diff --git a/.local/bin/flac2opus b/.local/bin/flac2opus
--- a/.local/bin/flac2opus
+++ b/.local/bin/flac2opus
@@ -18,18 +18,18 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -39,5 +39,5 @@ parallel
 EOF
 
 if ! parallel opusenc --bitrate 192 '{}' '{.}.opus' ::: ./*.flac; then
-  err 'Unable to convert from FLAC to opus.'
+    err 'Unable to convert from FLAC to opus.'
 fi
diff --git a/.local/bin/fzf-open b/.local/bin/fzf-open
--- a/.local/bin/fzf-open
+++ b/.local/bin/fzf-open
@@ -18,24 +18,24 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 usage() {
-  err "usage:
+    err "usage:
 ${0##*/} [command] [dir for fzf]"
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 [ -z "$1" ] && usage
diff --git a/.local/bin/genfavi b/.local/bin/genfavi
--- a/.local/bin/genfavi
+++ b/.local/bin/genfavi
@@ -18,24 +18,24 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 usage() {
-  err "usage:
+    err "usage:
 ${0##*/} [image]"
 }
 
 
 genfavi() {
-  convert "$1" -background white             \
-  \( -clone 0 -resize 16x16 -extent 16x16 \) \
-  \( -clone 0 -resize 32x32 -extent 32x32 \) \
-  \( -clone 0 -resize 48x48 -extent 48x48 \) \
-  \( -clone 0 -resize 64x64 -extent 64x64 \) \
-  -delete 0 -alpha off -colors 256 favicon.ico
+    convert "$1" -background white                 \
+        \( -clone 0 -resize 16x16 -extent 16x16 \) \
+        \( -clone 0 -resize 32x32 -extent 32x32 \) \
+        \( -clone 0 -resize 48x48 -extent 48x48 \) \
+        \( -clone 0 -resize 64x64 -extent 64x64 \) \
+        -delete 0 -alpha off -colors 256 favicon.ico
 }
 
 
@@ -44,14 +44,14 @@ genfavi() {
 [ -z "$1" ] && usage
 
 case "$(file -ib -- "$1")" in
-  image/*) :                        ;; # images are OK to process
-  *)       err "$1 isn't an image." ;;
+    image/*) :                        ;; # images are OK to process
+    *)       err "$1 isn't an image." ;;
 esac
 
 if genfavi "$1"; then
-  cp 'favicon.ico' 'favicon.png'
+    cp 'favicon.ico' 'favicon.png'
 
 else
-  err 'Unable to generate favicon.'
+    err 'Unable to generate favicon.'
 
 fi
diff --git a/.local/bin/maimpick b/.local/bin/maimpick
--- a/.local/bin/maimpick
+++ b/.local/bin/maimpick
@@ -7,51 +7,51 @@
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
 import_colors_sh() {
-  readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+    readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
 
-  if ! [ -r "${COLORS_SH}" ]; then
-    echo "${COLORS_SH} is not readable." >&2
+    if ! [ -r "${COLORS_SH}" ]; then
+        echo "${COLORS_SH} is not readable." >&2
 
-  elif ! [ -f "${COLORS_SH}" ]; then
-    echo "${COLORS_SH} is not a file." >&2
+    elif ! [ -f "${COLORS_SH}" ]; then
+        echo "${COLORS_SH} is not a file." >&2
 
-  # passed sanity checks, so source the file
-  else
-    . "${COLORS_SH}"
+    # passed sanity checks, so source the file
+    else
+        . "${COLORS_SH}"
 
-  fi
+    fi
 }
 
 
 menu() {
-  dmenu -i -fn 'mono-12'       \
-  -nb "${background:-#040516}" \
-  -nf "${color3:-#9974e7}"     \
-  -sb "${background:-#040516}" \
-  -sf "${foreground:-#e0cef3}" \
-  "$@"
+    dmenu -i -fn 'mono-12'           \
+        -nb "${background:-#040516}" \
+        -nf "${color3:-#9974e7}"     \
+        -sb "${background:-#040516}" \
+        -sf "${foreground:-#e0cef3}" \
+        "$@"
 }
 
 
 yankpic() {
-  xclip -selection clipboard -t image/png \
-    || err 'Unable to copy image data to clipboard.'
+    xclip -selection clipboard -t image/png \
+        || err 'Unable to copy image data to clipboard.'
 }
 
 
@@ -62,53 +62,53 @@ maim_with_flags() {
 
 
 present_options() {
-  case "$(menu -l "${NUM_OF_OPTS}" -p "Screenshot which area?")" in
+    case "$(menu -l "${NUM_OF_OPTS}" -p "Screenshot which area?")" in
 
-    'a selected area')
-      FILENAME="selected-$(date '+%Y%m%d-%H%M%S').png"
-      readonly FILENAME
+        'a selected area')
+            FILENAME="selected-$(date '+%Y%m%d-%H%M%S').png"
+            readonly FILENAME
 
-      maim_with_flags -s -- "${SAVEDIR}/${FILENAME}"
+            maim_with_flags -s -- "${SAVEDIR}/${FILENAME}"
 
-      ;;
+            ;;
 
-    'current window')
-      FILENAME="window-$(date '+%Y%m%d-%H%M%S').png"
-      readonly FILENAME
+        'current window')
+            FILENAME="window-$(date '+%Y%m%d-%H%M%S').png"
+            readonly FILENAME
 
-      maim_with_flags -i "$(xdotool getactivewindow)" -- "${SAVEDIR}/${FILENAME}"
+            maim_with_flags -i "$(xdotool getactivewindow)" -- "${SAVEDIR}/${FILENAME}"
 
-      ;;
+            ;;
 
-    'full screen')
-      FILENAME="full-$(date '+%Y%m%d-%H%M%S').png"
-      readonly FILENAME
+        'full screen')
+            FILENAME="full-$(date '+%Y%m%d-%H%M%S').png"
+            readonly FILENAME
 
-      maim_with_flags -- "${SAVEDIR}/${FILENAME}"
+            maim_with_flags -- "${SAVEDIR}/${FILENAME}"
 
-      ;;
+            ;;
 
-    'a selected area (copy)')
-      maim_with_flags -s | yankpic
+        'a selected area (copy)')
+            maim_with_flags -s | yankpic
 
-      ;;
+            ;;
 
-    'current window (copy)')
-      maim_with_flags -i "$(xdotool getactivewindow)" | yankpic
+        'current window (copy)')
+            maim_with_flags -i "$(xdotool getactivewindow)" | yankpic
 
-      ;;
+            ;;
 
-    'full screen (copy)')
-      maim_with_flags | yankpic
+        'full screen (copy)')
+            maim_with_flags | yankpic
 
-      ;;
+            ;;
 
-    *)
-      err 'Not a valid area.'
+        *)
+            err 'Not a valid area.'
 
-      ;;
+            ;;
 
-  esac
+    esac
 }
 
 
diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -18,13 +18,13 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 usage() {
-  err "usage:
+    err "usage:
 ${0##*/} [cue file] [FLAC file]
 
 -c : convert 24bit flac to 16bit before splitting (sox needed)
@@ -33,27 +33,27 @@ ${0##*/} [cue file] [FLAC file]
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
 # determines which executable name to use for cuetag.
 assign_cuetag() {
-  if [ -x "$(command -v -- 'cuetag')" ]; then
-    readonly CUETAG='cuetag'
+    if [ -x "$(command -v -- 'cuetag')" ]; then
+        readonly CUETAG='cuetag'
 
-  elif [ -x "$(command -v -- 'cuetag.sh')" ]; then
-    readonly CUETAG='cuetag.sh'
+    elif [ -x "$(command -v -- 'cuetag.sh')" ]; then
+        readonly CUETAG='cuetag.sh'
 
-  else
-    err 'Neither cuetag nor cuetag.sh found.'
+    else
+        err 'Neither cuetag nor cuetag.sh found.'
 
-  fi
+    fi
 }
 
 
@@ -61,40 +61,40 @@ assign_cuetag() {
 #
 # $1 is a FLAC file to be converted.
 conv16() {
-  STAGING_FILE="${1%.flac}-staging.flac"
-  readonly STAGING_FILE
+    STAGING_FILE="${1%.flac}-staging.flac"
+    readonly STAGING_FILE
 
-  # http://sox.sourceforge.net/Docs/FAQ
-  #
-  # according to sox(1), most noise shaping filters are only available
-  # at 44.1kHz, so that is the chosen sample rate.
-  if sox -SG "$1" -b 16 "${STAGING_FILE}" rate -v 44100 dither -s; then
-    [ "${DELETE}" = 'yes' ] && rm -- "$1"
-    [ -e "$1" ] && mv -- "$1" "$1-24bit.bak"
+    # http://sox.sourceforge.net/Docs/FAQ
+    #
+    # according to sox(1), most noise shaping filters are only available
+    # at 44.1kHz, so that is the chosen sample rate.
+    if sox -SG "$1" -b 16 "${STAGING_FILE}" rate -v 44100 dither -s; then
+        [ "${DELETE}" = 'yes' ] && rm -- "$1"
+        [ -e "$1" ] && mv -- "$1" "$1-24bit.bak"
 
-    mv -- "${STAGING_FILE}" "$1"
+        mv -- "${STAGING_FILE}" "$1"
 
-  else
-    err 'Failed to convert 24-bit FLAC file to 16-bit.'
+    else
+        err 'Failed to convert 24-bit FLAC file to 16-bit.'
 
-  fi
+    fi
 }
 
 
 splitflac() {
-  [ -e "$2.bak" ] && err "$2.bak exists, exiting to prevent clobbering."
+    [ -e "$2.bak" ] && err "$2.bak exists, exiting to prevent clobbering."
 
-  # spaces in shnsplit filename messes up cue tagging, so just leave
-  # the default in place. it's the only way to be sure that we won't run
-  # into that issue, because %t will often add spaces too.
-  if ! cuebreakpoints -- "$1" | shnsplit -o flac -- "$2"; then
-    err 'Unable to split the FLAC file.'
-  fi
+    # spaces in shnsplit filename messes up cue tagging, so just leave
+    # the default in place. it's the only way to be sure that we won't run
+    # into that issue, because %t will often add spaces too.
+    if ! cuebreakpoints -- "$1" | shnsplit -o flac -- "$2"; then
+        err 'Unable to split the FLAC file.'
+    fi
 
-  [ "${DELETE}" = 'yes' ] && rm -- "$2"
-  [ -e "$2" ] && mv -- "$2" "$2.bak"
+    [ "${DELETE}" = 'yes' ] && rm -- "$2"
+    [ -e "$2" ] && mv -- "$2" "$2.bak"
 
-  "${CUETAG}" "$1" ./*.flac || err 'Unable to tag FLAC files.'
+    "${CUETAG}" "$1" ./*.flac || err 'Unable to tag FLAC files.'
 }
 
 
@@ -109,11 +109,11 @@ EOF
 
 while getopts cd opt; do
 
-  case "${opt}" in
-    c) readonly CONVERT='yes' ;;
-    d) readonly DELETE='yes'  ;;
-    *) usage                  ;;
-  esac
+    case "${opt}" in
+        c) readonly CONVERT='yes' ;;
+        d) readonly DELETE='yes'  ;;
+        *) usage                  ;;
+    esac
 
 done
 
@@ -125,16 +125,16 @@ shift $((OPTIND - 1))
 assign_cuetag
 
 [ "${CONVERT}" = 'yes' ] && {
-  # makes sense to check dependency only when it's really needed
-  echo 'sox' | check_deps
-  conv16 "$2"
+    # makes sense to check dependency only when it's really needed
+    echo 'sox' | check_deps
+    conv16 "$2"
 }
 
 # checks for sector boundary errors and fixes them if they are present
 # before splitting the FLAC file.
 shnfix -c -- "$2" && {
-  shnfix -o flac -- "$2"
-  mv -- "${2%.flac}-fixed.flac" "$2"
+    shnfix -o flac -- "$2"
+    mv -- "${2%.flac}-fixed.flac" "$2"
 }
 
 CRLESS_CUESHEET="$(mktemp)"
diff --git a/.local/bin/viewimg b/.local/bin/viewimg
--- a/.local/bin/viewimg
+++ b/.local/bin/viewimg
@@ -18,34 +18,34 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 usage() {
-  err "usage:
+    err "usage:
 ${0##*/} [URL]"
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
 viewimg() {
-  FILENAME="$(mktemp)"
-  readonly FILENAME
+    FILENAME="$(mktemp)"
+    readonly FILENAME
 
-  ftp -nU '' -o "${FILENAME}" -- "$1"
+    ftp -nU '' -o "${FILENAME}" -- "$1"
 
-  sxiv -- "${FILENAME}"
+    sxiv -- "${FILENAME}"
 }
 
 
diff --git a/.local/bin/volman b/.local/bin/volman
--- a/.local/bin/volman
+++ b/.local/bin/volman
@@ -16,24 +16,24 @@
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+    printf '%s\n' "$*" >&2
+    exit 1
 }
 
 
 usage() {
-  err "usage:
+    err "usage:
 ${0##*/} [inc|dec|mute]"
 }
 
 
 check_deps() {
-  while read -r dependency; do
+    while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+        [ -x "$(command -v -- "${dependency}")" ] \
+            || err "${dependency} not found in PATH or not executable."
 
-  done
+    done
 }
 
 
@@ -52,47 +52,47 @@ adjust_vol() {
 # based on the current output level, print an appropriate volume-related
 # emoji. if output.mute=0, all positional parameters as well.
 print_vol() {
-  if [ "${MUTED}" = 'true' ]; then
-    echo '🔇 MUTED'
+    if [ "${MUTED}" = 'true' ]; then
+        echo '🔇 MUTED'
 
-  elif [ "${VOL}" -eq 0 ]; then
-    echo '🔇 ' "$@"
+    elif [ "${VOL}" -eq 0 ]; then
+        echo '🔇 ' "$@"
 
-  elif [ "${VOL}" -ge 50 ]; then
-    echo '🔊 ' "$@"
+    elif [ "${VOL}" -ge 50 ]; then
+        echo '🔊 ' "$@"
 
-  elif [ "${VOL}" -ge 25 ]; then
-    echo '🔉 ' "$@"
+    elif [ "${VOL}" -ge 25 ]; then
+        echo '🔉 ' "$@"
 
-  else
-    echo '🔈 ' "$@"
+    else
+        echo '🔈 ' "$@"
 
-  fi
+    fi
 }
 
 
 # if muted, succeed.
 # if not muted, fail.
 check_mute() {
-  case "$(sndioctl -n output.mute 2>/dev/null)" in
-    1) return 0                                 ;;
-    0) return 1                                 ;;
-    *) err 'Unable to access sndio(7) device.'  ;;
-  esac
+    case "$(sndioctl -n output.mute 2>/dev/null)" in
+        1) return 0                                 ;;
+        0) return 1                                 ;;
+        *) err 'Unable to access sndio(7) device.'  ;;
+    esac
 }
 
 
 # get raw output level and convert it to something more parsable.
 get_vol() {
-  RAW_VOL="$(sndioctl -n output.level 2>/dev/null)"
-  readonly RAW_VOL
+    RAW_VOL="$(sndioctl -n output.level 2>/dev/null)"
+    readonly RAW_VOL
 
-  case "${RAW_VOL}" in
-    1.000) echo 100                                                  ;;
-    0.000) echo 0                                                    ;;
-           # division is here to truncate the floating point number.
-    *)     printf 'scale=0; (%.2g * %s) / 1\n' "${RAW_VOL}" 100 | bc ;;
-  esac
+    case "${RAW_VOL}" in
+        1.000) echo 100                                                  ;;
+        0.000) echo 0                                                    ;;
+               # division is here to truncate the floating point number.
+        *)     printf 'scale=0; (%.2g * %s) / 1\n' "${RAW_VOL}" 100 | bc ;;
+    esac
 }
 
 
