follow google shell style guidelines

diff --git a/.local/bin/check-batt b/.local/bin/check-batt
--- a/.local/bin/check-batt
+++ b/.local/bin/check-batt
@@ -24,8 +24,8 @@ readonly DEPENDENCIES='apm
 notify-send'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 # If A/C is connected, exit.
@@ -40,7 +40,7 @@ esac
 BATT_PERCENT="$(apm -l)"
 readonly BATT_PERCENT
 
-[ "${BATT_PERCENT}" -lt 20 ] &&
-	exec notify-send -- "Your device is at ${BATT_PERCENT}%!"
+[ "${BATT_PERCENT}" -lt 20 ] \
+	&& exec notify-send -- "Your device is at ${BATT_PERCENT}%!"
 
 exit 0
diff --git a/.local/bin/clear_clip b/.local/bin/clear_clip
--- a/.local/bin/clear_clip
+++ b/.local/bin/clear_clip
@@ -25,8 +25,8 @@ readonly DEPENDENCIES='xclip
 notify-send'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 xclip -selection clipboard -i /dev/null || err 'Unable to clear the clipboard.'
diff --git a/.local/bin/comprimg b/.local/bin/comprimg
--- a/.local/bin/comprimg
+++ b/.local/bin/comprimg
@@ -40,8 +40,8 @@ readonly DEPENDENCIES='jpegoptim
 optipng'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 [ -n "$*" ] || usage
diff --git a/.local/bin/fzf-open b/.local/bin/fzf-open
--- a/.local/bin/fzf-open
+++ b/.local/bin/fzf-open
@@ -37,8 +37,8 @@ readonly DEPENDENCIES="fzf
 $1"
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 cd "$2" || err "Could not change directory to $2"
diff --git a/.local/bin/launch-element-web b/.local/bin/launch-element-web
--- a/.local/bin/launch-element-web
+++ b/.local/bin/launch-element-web
@@ -33,8 +33,8 @@ ${BROWSER}
 ${HANDLER}"
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 [ -n "${DISPLAY}" ] || err "${0##*/} needs a graphical environment."
diff --git a/.local/bin/maimpick b/.local/bin/maimpick
--- a/.local/bin/maimpick
+++ b/.local/bin/maimpick
@@ -22,8 +22,8 @@ menu() {
 }
 
 yankpic() {
-	xclip -selection clipboard -t image/png ||
-		err 'Unable to copy image data to clipboard.'
+	xclip -selection clipboard -t image/png \
+		|| err 'Unable to copy image data to clipboard.'
 }
 
 # --hide-cursor, --quiet, --capturebackground, --delay
@@ -78,8 +78,8 @@ xclip
 xdotool'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 [ -n "${DISPLAY}" ] || err "${0##*/} requires a graphical environment."
diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -93,8 +93,8 @@ readonly DEPENDENCIES='flac
 shntool'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 if command -v 'cuetag' > /dev/null 2>&1; then
diff --git a/.local/bin/volman b/.local/bin/volman
--- a/.local/bin/volman
+++ b/.local/bin/volman
@@ -75,8 +75,8 @@ dunstify
 sndioctl'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" > /dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
+	command -v -- "${dependency}" > /dev/null 2>&1 \
+		|| err "${dependency} not found in PATH."
 done
 
 adjust_volume "$1"
