.local/bin/{check-batt,clear_clip,dmenuunicode,filehandler}:
begin the process of migrating away from common.sh since it reduces
portability.

diff --git a/.local/bin/check-batt b/.local/bin/check-batt
--- a/.local/bin/check-batt
+++ b/.local/bin/check-batt
@@ -14,51 +14,49 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
-
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
+}
 
-fi
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
 
 
-# handle prerequisites. designed to exit if prerequisites aren't in
-# place so that the script behaves more predictably.
-prereqs() {
-  # if needed dependencies aren't available, exit.
-  check_deps <<'EOF'
+# if needed dependencies aren't available, exit.
+check_deps <<'EOF'
 apm
 notify-send
 EOF
 
-  # if A/C is connected, exit.
-  [ "$(apm -a)" = 1 ] && exit
+# if A/C is connected, exit.
+[ "$(apm -a)" = 1 ] && exit 0
 
-  # if battery is missing, exit.
-  batt_status="$(apm -b)"
+# if battery is missing, exit.
+batt_status="$(apm -b)"
 
-  case "${batt_status}" in
-    4)   err "Battery status is 'absent.'"  ;;
-    255) err "Battery status is 'unknown.'" ;;
-  esac
-}
-
-
-prereqs
+case "${batt_status}" in
+  4)   err "Battery status is 'absent.'"  ;;
+  255) err "Battery status is 'unknown.'" ;;
+esac
 
 batt_percent="$(apm -l)"
 
 if [ "${batt_percent}" -lt 20 ]; then
   # exporting ${DISPLAY} is needed for cron(8) jobs.
-  [ -z "${DISPLAY}" ] && export DISPLAY=:0
+  [ -z "${DISPLAY}" ] && : "${DISPLAY:=:0}" && export DISPLAY
 
   notify-send -- "🔋 Your device is at ${batt_percent}%!"
 
diff --git a/.local/bin/clear_clip b/.local/bin/clear_clip
--- a/.local/bin/clear_clip
+++ b/.local/bin/clear_clip
@@ -16,32 +16,33 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
-
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
-
-fi
-
-
-prereqs() {
-  check_deps <<'EOF'
-xclip
-notify-send
-EOF
 }
 
 
-prereqs
-yank -i /dev/null || err 'Unable to clear the clipboard.'
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
+
+
+check_deps <<'EOF'
+xclip
+notify-send
+EOF
+
+xclip -selection clipboard -i /dev/null || err 'Unable to clear the clipboard.'
 
 case "$1" in
   'notify') notify-send '📋 Cleared the clipboard.'             ;;
diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -7,24 +7,59 @@
 # his dotfiles can be accessed here:
 # https://github.com/LukeSmithxyz/voidrice
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
+}
 
-fi
+
+menu() {
+  dmenu -i -fn 'mono-12'       \
+  -nb "${background:=#040516}" \
+  -nf "${color3:=#9974e7}"     \
+  -sb "${background:=#040516}" \
+  -sf "${foreground:=#e0cef3}" \
+  "$@"
+}
+
+
+import_colors_sh() {
+  COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+
+  if ! [ -r "${COLORS_SH}" ]; then
+    : "${DOTFILES_LOG:=${XDG_DATA_HOME:=${HOME}/.local/share}/dotfiles.log}"
+    echo "${COLORS_SH} not readable." 2>>"${DOTFILES_LOG}" >&2
+
+  elif ! [ -f "${COLORS_SH}" ]; then
+    : "${DOTFILES_LOG:=${XDG_DATA_HOME:=${HOME}/.local/share}/dotfiles.log}"
+    echo "${COLORS_SH} not a file." 2>>"${DOTFILES_LOG}" >&2
+
+  # passed sanity checks, so source the file
+  else
+    . "${COLORS_SH}"
+
+  fi
+}
+
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
 
 
 grab_emoji() {
-  readonly EMOJI_FILE="${XDG_DATA_HOME}/emoji"
+  readonly EMOJI_FILE="${XDG_DATA_HOME:=${HOME}/.local/share}/emoji"
   [ -f "${EMOJI_FILE}" ] || err "${EMOJI_FILE} is not a file."
   [ -r "${EMOJI_FILE}" ] || err "${EMOJI_FILE} is not readable."
 
@@ -42,7 +77,7 @@ grab_emoji() {
   # also important to not send a newline to yank() aka xclip(1),
   # otherwise pasting from the clipboard in certain messengers will send
   # the message.
-  if printf '%s' "${emoji}" | yank; then
+  if printf '%s' "${emoji}" | xclip -selection clipboard; then
     notify-send -- "${emoji} copied to clipboard."
 
   else
@@ -52,18 +87,14 @@ grab_emoji() {
 }
 
 
-prereqs() {
-  check_grafix
+[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
 
-  check_deps <<'EOF'
+check_deps <<'EOF'
 dmenu
 notify-send
 xclip
 EOF
 
-  import_colors_sh
-}
+import_colors_sh
 
-
-prereqs
 grab_emoji
diff --git a/.local/bin/filehandler b/.local/bin/filehandler
--- a/.local/bin/filehandler
+++ b/.local/bin/filehandler
@@ -16,26 +16,15 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
-
-fi
+}
 
 
 usage() {
   cat >&2 <<EOF
-${0##*/} requires ${args_needed} argument(s).
-
 usage:
 ${0##*/} [options] [file]
 
@@ -56,6 +45,64 @@ ${0##*/} only processes the first operation it sees.
 EOF
 
   exit 1
+}
+
+
+args_needed() {
+  case "$1" in
+
+    ''|*[!0-9]*)
+      err "args_needed() needs a number." >&2
+
+      ;;
+
+  esac
+
+  err "$1 argument(s) required by ${0##*/}."
+}
+
+
+menu() {
+  dmenu -i -fn 'mono-12'       \
+  -nb "${background:=#040516}" \
+  -nf "${color3:=#9974e7}"     \
+  -sb "${background:=#040516}" \
+  -sf "${foreground:=#e0cef3}" \
+  "$@"
+}
+
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
+
+
+import_colors_sh() {
+  COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+
+  if ! [ -r "${COLORS_SH}" ]; then
+    : "${DOTFILES_LOG:=${XDG_DATA_HOME:=${HOME}/.local/share}/dotfiles.log}"
+    echo "${COLORS_SH} not readable." 2>>"${DOTFILES_LOG}" >&2
+
+  elif ! [ -f "${COLORS_SH}" ]; then
+    : "${DOTFILES_LOG:=${XDG_DATA_HOME:=${HOME}/.local/share}/dotfiles.log}"
+    echo "${COLORS_SH} not a file." 2>>"${DOTFILES_LOG}" >&2
+
+  # passed sanity checks, so source the file
+  else
+    . "${COLORS_SH}"
+
+  fi
 }
 
 
@@ -165,24 +212,13 @@ rename_file() {
   fi
 }
 
-prereqs1() {
-  check_grafix
-  check_deps <<'EOF'
+
+[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
+
+check_deps <<'EOF'
 dmenu
 notify-send
 EOF
-}
-
-
-prereqs2() {
-  [ "$#" = "${args_needed}" ] || usage
-  import_colors_sh
-  [ -f "$1" ] || err 'Not a file or does not exist.'
-}
-
-
-prereqs1
-readonly args_needed=1
 
 while getopts chmn opt; do
 
@@ -197,7 +233,9 @@ done
 
 shift $((OPTIND - 1))
 
-prereqs2 "$@"
+[ "$#" = 1 ] || args_needed 1
+import_colors_sh
+[ -f "$1" ] || err 'Not a file or does not exist.'
 
 file="$(readlink -f -- "$1")"
 readonly file
