remove this recurring if conditional and replace it with '||' since this extra handling is unneeded

diff --git a/.local/bin/clear_clip b/.local/bin/clear_clip
--- a/.local/bin/clear_clip
+++ b/.local/bin/clear_clip
@@ -25,13 +25,8 @@ err() {
 check_deps() {
   while read -r dependency; do
 
-    if [ -x "$(command -v -- "${dependency}")" ]; then
-      continue
-
-    else
-      err "${dependency} not found in PATH or not executable."
-
-    fi
+    [ -x "$(command -v -- "${dependency}")" ] \
+      || err "${dependency} not found in PATH or not executable."
 
   done
 }
diff --git a/.local/bin/volman b/.local/bin/volman
--- a/.local/bin/volman
+++ b/.local/bin/volman
@@ -30,13 +30,8 @@ ${0##*/} [inc|dec|mute]"
 check_deps() {
   while read -r dependency; do
 
-    if [ -x "$(command -v -- "${dependency}")" ]; then
-      continue
-
-    else
-      err "${dependency} not found in PATH or not executable."
-
-    fi
+    [ -x "$(command -v -- "${dependency}")" ] \
+      || err "${dependency} not found in PATH or not executable."
 
   done
 }
