various: I don't believe in main() anymore. I think most scripts are more readable without it if it's just encapsulating everything after all the other functions are defined

diff --git a/.local/bin/clear_clip b/.local/bin/clear_clip
--- a/.local/bin/clear_clip
+++ b/.local/bin/clear_clip
@@ -36,16 +36,10 @@ notify-send
 EOF
 }
 
-# clears the clipboard.
-# if 'notify' is the first argument, clear_clip will notify the user.
-main() {
-  prereqs
-  yank -i /dev/null || err 'Unable to clear the clipboard.'
+prereqs
+yank -i /dev/null || err 'Unable to clear the clipboard.'
 
-  case "$1" in
-    'notify') notify-send '📋 Cleared the clipboard.'             ;;
-    *)        # undefined positional parameters should do nothing ;;
-  esac
-}
-
-main "$@"
+case "$1" in
+  'notify') notify-send '📋 Cleared the clipboard.'             ;;
+  *)        # undefined positional parameters should do nothing ;;
+esac
diff --git a/.local/bin/nsc b/.local/bin/nsc
--- a/.local/bin/nsc
+++ b/.local/bin/nsc
@@ -57,12 +57,11 @@ prereqs() {
   [ "$#" -ge "${args_needed}" ] || usage
 }
 
-main() {
-  prereqs "$@"
-  tmpdir="$(mktemp -d)" && readonly tmpdir
-  nsc "$@" || err 'Unable to scan target.'
-  fix_perms || err 'Unable to fix permissions.'
-  echo "Scan finished, results available in ${tmpdir}."
-}
+prereqs "$@"
 
-main "$@"
+tmpdir="$(mktemp -d)" && readonly tmpdir
+
+nsc "$@" || err 'Unable to scan target.'
+fix_perms || err 'Unable to fix permissions.'
+
+echo "Scan finished, results available in ${tmpdir}."
diff --git a/.local/bin/webtest b/.local/bin/webtest
--- a/.local/bin/webtest
+++ b/.local/bin/webtest
@@ -63,20 +63,22 @@ EOF
   [ "$#" = "${args_needed}" ] || usage
 }
 
-# TODO: a conf file is likely a better implementation than positional
-# parameters in the long run.
-main() {
-  umask 022
-  prereqs "$@"
-  readonly site="$1"
-  readonly markdowndir="$2"
-  readonly srvdir="$3"
-  htmldir="$(mktemp -d)" && readonly htmldir
-  readonly unpriv_user="${LOGNAME}"
-  gen_site || { cleanup; err 'Unable to generate site.'; }
-  sync_site || { cleanup; err 'Unable to sync web server.'; }
+umask 022
+prereqs "$@"
+
+readonly site="$1"
+readonly markdowndir="$2"
+readonly srvdir="$3"
+htmldir="$(mktemp -d)" && readonly htmldir
+readonly unpriv_user="${LOGNAME}"
+
+if ! gen_site; then
+  cleanup
+  err 'Unable to generate site.'
+elif ! sync_site; then
+  cleanup
+  err 'Unable to sync web server.'
+else
   cleanup
   echo 'Web server synced.'
-}
-
-main "$@"
+fi
