dmenuunicode: added '--' where appropriate

diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -14,7 +14,7 @@ readonly library="${HOME}/.local/bin/common.sh"
 if [ -r "${library}" ]; then
   . "${library}"
 else
-  cat >&2 <<EOF
+  cat >&2 -- <<EOF
 ${library} doesn't exist or isn't readable.
 ${0##*/} may not function correctly without it; exiting for safety.
 EOF
@@ -25,13 +25,13 @@ grab_emoji() {
   readonly emoji_file="${HOME}/.local/share/emoji"
   [ -r "${emoji_file}" ] || err "Emoji file isn't available."
 
-  readonly chosen="$(cut -d ';' -f1 "${emoji_file}" | menu -l 20)"
+  readonly chosen="$(cut -d ';' -f1 -- "${emoji_file}" | menu -l 20)"
   [ -n "${chosen}" ] || err 'Must choose an emoji.'
-  grep -q "^${chosen}" "${emoji_file}" || err 'Emoji not found.'
+  grep -q -- "^${chosen}" "${emoji_file}" || err 'Emoji not found.'
 
   # important to use printf %s here, as ${chosen} is user input
   if printf '%s' "${chosen%% *}" | yank; then
-    notify-send "${chosen%% *} copied to clipboard."
+    notify-send -- "${chosen%% *} copied to clipboard."
   else
     err 'Unable to grab emoji.'
   fi
