dunstrc: removes config values that reflect defaults
dmenuunicode: sends a notification, more specific grep(1) check

diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -27,10 +27,14 @@ grab_emoji() {
 
   readonly chosen="$(cut -d ';' -f1 "${emoji_file}" | menu -l 20)"
   [ -n "${chosen}" ] || err 'Must choose an emoji.'
-  grep -q "${chosen}" "${emoji_file}" || err 'Emoji not found.'
+  grep -q "^${chosen}" "${emoji_file}" || err 'Emoji not found.'
 
   # important to use printf %s here, as ${chosen} is user input
-  printf '%s' "${chosen%% *}" | yank
+  if printf '%s' "${chosen%% *}" | yank; then
+    notify-send "${chosen%% *} copied to clipboard."
+  else
+    err 'Unable to grab emoji.'
+  fi
 }
 
 main() { check_grafix; import_colors; grab_emoji; }; main
