dmenuunicode: better error messages

diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -28,13 +28,13 @@ grab_emoji() {
   chosen="$(cut -d ';' -f1 -- "${emoji_file}" | menu -l 20)"
   [ -n "${chosen}" ] || err 'Must choose an emoji.'
   readonly chosen="${chosen%% *}"
-  grep -q -- "^${chosen}" "${emoji_file}" || err 'Emoji not found.'
+  grep -q -- "^${chosen}" "${emoji_file}" || err "Emoji not found in ${emoji_file}."
 
   # important to use printf %s here, as ${chosen} is user input
   if printf '%s' "${chosen}" | yank; then
     notify-send -- "${chosen} copied to clipboard."
   else
-    err 'Unable to grab emoji.'
+    err 'Unable to grab emoji with xclip(1).'
   fi
 }
 
