cleanup

diff --git a/.local/bin/dmenuunicode b/.local/bin/dmenuunicode
--- a/.local/bin/dmenuunicode
+++ b/.local/bin/dmenuunicode
@@ -7,12 +7,12 @@
 # his dotfiles can be accessed here:
 # https://github.com/LukeSmithxyz/voidrice
 
+set -e
 
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
 }
-
 
 menu() {
 	dmenu -i -l 20 \
@@ -25,68 +25,34 @@ menu() {
 }
 
 
-import_colors_sh() {
-	readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+readonly COLORS_SH="${XDG_CACHE_HOME:-${HOME}/.cache}/wal/colors.sh"
 
-	if ! [ -r "${COLORS_SH}" ]; then
-		echo "${COLORS_SH} is not readable." >&2
+readonly DEPENDENCIES='dmenu
+notify-send
+xclip'
 
-	elif ! [ -f "${COLORS_SH}" ]; then
-		echo "${COLORS_SH} is not a file." >&2
-
-	# passed sanity checks, so source the file
-	else
-		. "${COLORS_SH}"
-
-	fi
-}
+readonly EMOJI_FILE="${XDG_DATA_HOME:-${HOME}/.local/share}/emoji"
 
 
-check_deps() {
-	while read -r dependency; do
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
+done
 
-		[ -x "$(command -v -- "${dependency}")" ] \
-			|| err "${dependency} not found in PATH or not executable."
+[ -n "${DISPLAY}" ] || err "${0##*/} requires a graphical environment."
 
-	done
-}
-
-
-[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
-
-
-check_deps <<-'EOF'
-	dmenu
-	notify-send
-	xclip
-EOF
-
-
-import_colors_sh
-
-
-readonly EMOJI_FILE="${XDG_DATA_HOME:=${HOME}/.local/share}/emoji"
-[ -r "${EMOJI_FILE}" ] || err "${EMOJI_FILE} is not readable."
-[ -f "${EMOJI_FILE}" ] || err "${EMOJI_FILE} is not a file."
+. "${COLORS_SH}"
 
 
 CHOSEN_ENTRY="$(cut -d ';' -f 1 -- "${EMOJI_FILE}" | menu)"
 readonly CHOSEN_ENTRY
 [ -n "${CHOSEN_ENTRY}" ] || err 'Must choose an emoji.'
 
-
 readonly EMOJI="${CHOSEN_ENTRY%% *}"
-grep -q -- "^${EMOJI}" "${EMOJI_FILE}" || err "Emoji not found in ${EMOJI_FILE}."
+grep -Fq -- "${EMOJI}" "${EMOJI_FILE}" || err "Emoji not found in ${EMOJI_FILE}."
 
 
-# important to use 'printf %s' here, as ${EMOJI} is user input
-#
-# also important to not send a newline to xclip(1), otherwise pasting
-# from the clipboard in certain messengers will send the message.
-if printf '%s' "${EMOJI}" | xclip -selection clipboard; then
-	notify-send 'Emoji copied to clipboard.'
+printf '%s' "${EMOJI}" | xclip -selection clipboard &&
+	exec notify-send 'Emoji copied to clipboard.'
 
-else
-	err 'Unable to grab emoji with xclip(1).'
-
-fi
+err 'Unable to grab emoji with xclip(1).'
