filehandler: readonly consistency changes. catch-all pattern removed, the code that was there now simply runs below instead of within the case statement.

diff --git a/.local/bin/filehandler b/.local/bin/filehandler
--- a/.local/bin/filehandler
+++ b/.local/bin/filehandler
@@ -62,7 +62,8 @@ EOF
 
 # assigns a value to ${preload_dir} based on the file's mimetype.
 determine_preload_dir() {
-  mimetype="$(file -ib -- "${file}")" && readonly mimetype
+  mimetype="$(file -ib -- "${file}")"
+  readonly mimetype
 
   case "${mimetype}" in
     # these are organized alphabetically by mimetype
@@ -102,22 +103,20 @@ move_file() {
 
       ;;
 
-    *)
-      no_tilde_dest="$(echo "${tilde_dest}" | sed -- "s|^~|${HOME}|g")"
-
-      mkdir -p -- "${no_tilde_dest}" || err "${tilde_dest} could not be created with mkdir(1)."
-
-      if mv -- "${file}" "${no_tilde_dest}/${file##*/}"; then
-        notify-send -- "${file##*/} moved to ${tilde_dest}"
-
-      else
-        err "Failed to move ${file##*/}"
-
-      fi
-
-    ;;
-
   esac
+
+  no_tilde_dest="$(echo "${tilde_dest}" | sed -- "s|^~|${HOME}|g")"
+
+  mkdir -p -- "${no_tilde_dest}" || err "${tilde_dest} could not be created with mkdir(1)."
+
+  if mv -- "${file}" "${no_tilde_dest}/${file##*/}"; then
+    notify-send -- "${file##*/} moved to ${tilde_dest}"
+
+  else
+    err "Failed to move ${file##*/}"
+
+  fi
+
 }
 
 
@@ -207,5 +206,7 @@ shift $((OPTIND - 1))
 
 prereqs2 "$@"
 
-file="$(readlink -f -- "$1")" && readonly file
+file="$(readlink -f -- "$1")"
+readonly file
+
 choose_operation
