clean up filehandler, adjust nsxiv config

diff --git a/.local/bin/filehandler b/.local/bin/filehandler
--- a/.local/bin/filehandler
+++ b/.local/bin/filehandler
@@ -14,35 +14,29 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-set -e
+set -ex
 
+readonly PROGRAM_NAME="${0##*/}"
 
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
 }
 
-
 usage() {
-	err "usage:
-${0##*/} [options] [file]
+	cat >&2 <<EOF
+usage:
+${PROGRAM_NAME} [operation] [file]
 
-options:
--h: help
--c: copy file (operation)
--m: move file (operation)
--n: rename file (operation)
+operations:
+help - display help
+copy - copy file
+move - move file
+rename - rename and then move file
+EOF
 
-If invoked without any options, ${0##*/} behaves interactively and asks
-the user for an operation.
-
-If an operation is specified, ${0##*/} skips the operation query and
-moves on to the next prompt.
-
-Note that only one operation should be specified at a time. In fact,
-${0##*/} only processes the first operation it sees."
+	exit 1
 }
-
 
 menu() {
 	dmenu -i -fn 'mono-12' \
@@ -53,186 +47,121 @@ menu() {
 		"$@"
 }
 
+print_preload_dir() {
+	readonly FILE_TO_EXAMINE="$1"
 
-check_deps() {
-	while read -r dependency; do
-
-		[ -x "$(command -v -- "${dependency}")" ] \
-			|| err "${dependency} not found in PATH or not executable."
-
-	done
-}
-
-
-import_colors_sh() {
-	readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
-
-	if ! [ -r "${COLORS_SH}" ]; then
-		echo "${COLORS_SH} is not readable." >&2
-
-	elif ! [ -f "${COLORS_SH}" ]; then
-		echo "${COLORS_SH} is not a file." >&2
-
-	# passed sanity checks, so source the file
-	else
-		. "${COLORS_SH}"
-
-	fi
-}
-
-
-# assigns a value to ${preload_dir} based on the file's mimetype.
-determine_preload_dir() {
-	MIMETYPE="$(file -ib -- "${FILE}")"
+	MIMETYPE="$(file -ib -- "${FILE_TO_EXAMINE}")"
 	readonly MIMETYPE
 
 	case "${MIMETYPE}" in
-		# these are organized alphabetically by mimetype
-		application/epub*) readonly PRELOAD_DIR="${HOME}/books" ;;
-		application/pdf*) readonly PRELOAD_DIR="${HOME}/books" ;;
-		image/vnd.djvu) readonly PRELOAD_DIR="${HOME}/books" ;;
-		image/*) readonly PRELOAD_DIR="${HOME}/pics" ;;
-		video/*) readonly PRELOAD_DIR="${HOME}/videos" ;;
-		*) err "No preload directory for this filetype." ;;
+		application/epub) echo "${HOME}/books" ;;
+		application/pdf) echo "${HOME}/books" ;;
+		image/vnd.djvu) echo "${HOME}/books" ;;
+		image/*) echo "${HOME}/pics" ;;
+		video/*) echo "${HOME}/videos" ;;
+		*) err 'No preload directory for this filetype.' ;;
 	esac
 }
 
+handle_destination() {
+	readonly FILE_WITHOUT_DESTINATION="$1"
+	BASENAME="${FILE_WITHOUT_DESTINATION##*/}"
 
-move_file() {
-	if mv -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
-		notify-send -- "${FILE##*/} moved to ${TILDE_DEST}"
+	PRELOAD_DIR="$(print_preload_dir "${FILE_WITHOUT_DESTINATION}")"
+	readonly PRELOAD_DIR
 
-	else
-		err "Failed to move ${FILE##*/}"
-
-	fi
-}
+	[ -d "${PRELOAD_DIR}" ] || err "'${PRELOAD_DIR}' is not a directory."
 
 
-copy_file() {
-	if cp -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
-		notify-send -- "${FILE##*/} copied to ${TILDE_DEST}"
-
-	else
-		err "Failed to copy ${FILE##*/}"
-
-	fi
-}
-
-
-# uses ${preload_dir} to display a list of directories that a given file
-# can be moved to. once the user chooses a destination with dmenu, move
-# the file there and send a notification.
-handle_dest() {
-	determine_preload_dir
-
-	# substitutes $HOME with a tilde so the list of directories in dmenu is
-	# more readable.
-	TILDE_DEST="$(
-		{ find "${PRELOAD_DIR}" -type d | sed -- "s|^${HOME}|~|g"
-			echo 'exit'
-		} | menu -l 10 -p "Where should ${FILE##*/} be placed?"
+	# Substitute ${HOME} with a tilde so the list of directories in
+	# dmenu is more readable.
+	DESTINATION="$(
+		{
+		find "${PRELOAD_DIR}" -type d | sed "s|^${HOME}|~|g"
+		echo 'exit'
+		} | menu -l 10 -p "Where should ${BASENAME} be placed?"
 	)"
 
-	readonly TILDE_DEST
+	[ -n "${DESTINATION}" ] || err "${PROGRAM_NAME} needs a destination."
+	[ "${DESTINATION}" = 'exit' ] && exit
 
 
-	case "${TILDE_DEST}" in
+	# Revert prior substitution.
+	DESTINATION="$(echo "${DESTINATION}" | sed -- "s|^~|${HOME}|g")"
+	readonly DESTINATION
 
-		'exit')
-			exit 0
-
-			;;
-
-		'')
-			err "${0##*/} needs a destination."
-
-			;;
-
-	esac
-
-
-	NO_TILDE_DEST="$(echo "${TILDE_DEST}" | sed -- "s|^~|${HOME}|g")"
-	readonly NO_TILDE_DEST
-
-	mkdir -p -- "${NO_TILDE_DEST}" || err "${TILDE_DEST} could not be created with mkdir(1)."
+	mkdir -p -- "${DESTINATION}" ||
+		err "Failed to create directory '${DESTINATION}'."
 }
 
+copy_file() {
+	readonly FILE_TO_COPY="$1"
+	handle_destination "${FILE_TO_COPY}"
+	readonly BASENAME
 
-# once the user chooses a filename with dmenu, rename the file
-# accordingly and send a notification.
-#
-# dmenu seems to need at least one item from STDIN to behave properly.
+	cp -- "$1" "${DESTINATION}/${BASENAME}" && {
+		notify-send -- "'${BASENAME}' copied to '${DESTINATION}'"
+		return
+	}
+
+	err "Failed to copy '${BASENAME}'"
+}
+
+move_file() {
+	readonly FILE_TO_MOVE="$1"
+
+	# This may have been handled by rename_file already.
+	[ -z "${DESTINATION}" ] && handle_destination "${FILE_TO_MOVE}"
+	readonly BASENAME
+
+	mv -- "$1" "${DESTINATION}/${BASENAME}" && {
+		notify-send -- "'${BASENAME}' moved to '${DESTINATION}'"
+		return
+	}
+
+	err "Failed to move '${BASENAME}'"
+}
+
 rename_file() {
-	NEW_FILENAME="$(echo 'exit' | menu -p "Rename ${FILE##*/} to what?")"
-	readonly NEW_FILENAME
+	readonly FILE_TO_RENAME="$1"
+	handle_destination "${FILE_TO_RENAME}"
 
-	case "${NEW_FILENAME}" in
+	BASENAME="$(echo 'exit' | menu -p "Rename '${BASENAME}' to what?")"
 
-		'exit')
-			exit 0
+	[ -n "${BASENAME}" ] ||
+		err "${PROGRAM_NAME} needs a new name to rename '${BASENAME}' to."
 
-			;;
+	[ "${BASENAME}" = 'exit' ] && exit
 
-		'')
-			err "${0##*/} needs a new name to rename ${FILE##*/} to."
-
-			;;
-
-	esac
-
-	if mv -- "${FILE}" "${FILE%/*}/${NEW_FILENAME}"; then
-		notify-send -- "${FILE##*/} renamed to ${NEW_FILENAME}"
-
-	else
-		err "Failed to rename ${FILE}."
-
-	fi
+	move_file "${FILE_TO_RENAME}"
 }
 
 
-[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
+readonly COLORS_SH="${XDG_CACHE_HOME:-${HOME}/.cache}/wal/colors.sh"
 
-check_deps <<-'EOF'
-	dmenu
-	notify-send
-EOF
+readonly DEPENDENCIES='dmenu
+notify-send'
 
-while getopts chmn opt; do
-
-	case "${opt}" in
-		'c') readonly OPERATION='copy'; break ;;
-		'm') readonly OPERATION='move'; break ;;
-		'n') readonly OPERATION='rename'; break ;;
-		'h'|*) usage ;;
-	esac
-
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
 done
 
-shift $((OPTIND - 1))
 
-[ -z "$1" ] && usage
-import_colors_sh
-[ -f "$1" ] || err 'Not a file or does not exist.'
-
-FILE="$(readlink -f -- "$1")"
-readonly FILE
+[ -n "$1" ] || usage
+[ -n "$2" ] || usage
+[ -n "${DISPLAY}" ] || err "${PROGRAM_NAME} requires a graphical environment."
+. "${COLORS_SH}"
 
 
-# if there is no operation, prompt the user to select one.
-if [ -z "${OPERATION}" ]; then
-	OPERATION="$(printf '%s\n' 'copy' 'move' 'rename' | menu -p "What to do with ${FILE}?")"
-	readonly OPERATION
+FILE_TO_HANDLE="$(readlink -f -- "$2")"
+readonly FILE_TO_HANDLE
 
-	# a small delay needs to be here. without it, the subsequent menu
-	# won't appear sometimes.
-	sleep 0.25
-fi
-
+readonly OPERATION="$1"
 
 case "${OPERATION}" in
-	'copy') handle_dest && copy_file ;;
-	'move') handle_dest && move_file ;;
-	'rename') rename_file ;;
-	*) usage ;;
+	'copy') copy_file "${FILE_TO_HANDLE}" ;;
+	'move') move_file "${FILE_TO_HANDLE}" ;;
+	'rename') rename_file "${FILE_TO_HANDLE}" ;;
+	'help'|*) usage ;;
 esac
