various: readability changes

diff --git a/.local/bin/filehandler b/.local/bin/filehandler
--- a/.local/bin/filehandler
+++ b/.local/bin/filehandler
@@ -19,14 +19,18 @@ set -e
 # functions are available. if not, exit due to potentially unpredictable
 # behavior.
 readonly library="${HOME}/.local/bin/common.sh"
+
 if [ -r "${library}" ]; then
   . "${library}"
+
 else
   cat >&2 <<EOF
 ${library} doesn't exist or isn't readable.
 ${0##*/} may not function correctly without it; exiting for safety.
 EOF
+
   exit 1
+
 fi
 
 usage() {
@@ -72,12 +76,16 @@ determine_preload_dir() {
 move_file() {
   determine_preload_dir
   dest="$(
+
     {
-      # tilde expansion with sed for readability in dmenu
+
       find "${preload_dir}" -type d ! \( -name '.*' -prune \) \
         | sed -- "s|${HOME}|~|g"
+
       echo 'exit';
+
     } | menu -l 10 -p "Move ${file##*/} where?"
+
   )"
 
   [ "${dest}" = 'exit' ] && exit 0
@@ -87,16 +95,15 @@ move_file() {
   # with parameter expansion in the form "~${dest##${HOME}}"
   dest="$(echo "${dest}" | sed -- "s|~|${HOME}|g")"
 
-  if [ -d "${dest}" ] || mkdir -p -- "${dest}"; then
+  if ! [ -d "${dest}" ] || ! mkdir -p -- "${dest}"; then
+    err "~${dest##${HOME}} not found nor created."
 
-    if mv -- "${file}" "${dest}/${file##*/}"; then
-      notify-send -- "${file##*/} moved to ~${dest##${HOME}}"
-    else
-      err "Failed to move ${file##*/}"
-    fi
+  elif mv -- "${file}" "${dest}/${file##*/}"; then
+    notify-send -- "${file##*/} moved to ~${dest##${HOME}}"
 
   else
-    err "~${dest##${HOME}} not found nor created."
+    err "Failed to move ${file##*/}"
+
   fi
 }
 
@@ -107,17 +114,19 @@ move_file() {
 rename_file() {
   new_filename="$(echo 'exit' | menu -p "Rename ${file##*/} to what?")" \
     && readonly new_filename
-  if [ -n "${new_filename}" ]; then
-    [ "${new_filename}" = 'exit' ] && exit 0
 
-    if mv -- "${file}" "${file%/*}/${new_filename}"; then
-      notify-send -- "${file##*/} renamed to ${new_filename}"
-    else
-      err "Failed to rename ${file}."
-    fi
+  if [ "${new_filename}" = 'exit' ]; then
+    exit 0
+
+  elif [ -z "${new_filename}" ]; then
+    err "${0##*/} needs a new name to rename ${file##*/} to."
+
+  elif mv -- "${file}" "${file%/*}/${new_filename}"; then
+    notify-send -- "${file##*/} renamed to ${new_filename}"
 
   else
-    err "${0##*/} needs a new name to rename ${file##*/} to."
+    err "Failed to rename ${file}."
+
   fi
 }
 
@@ -125,14 +134,15 @@ rename_file() {
 # ${operation} by getopts, the user chooses the operation with dmenu.
 choose_operation() {
   if [ -z "${operation}" ]; then
-    readonly options='move
-rename'
-    operation="$(echo "${options}" | menu -p "What to do with ${file}?")" \
-      && readonly operation
+    readonly options='move\nrename'
+
+    operation="$(echo "${options}" | menu -p "What to do with ${file}?")"
+    readonly operation
 
     # a small delay needs to be here. without it, the subsequent menu
     # won't appear sometimes.
     sleep 0.3
+
   fi
 
   case "${operation}" in
@@ -160,13 +170,16 @@ prereqs1
 readonly args_needed=1
 
 while getopts hmn opt; do
+
   case "${opt}" in
     'h') usage                                ;;
     'm') readonly operation='move' && break   ;;
     'n') readonly operation='rename' && break ;;
     *)   usage                                ;;
   esac
+
 done
+
 shift $((OPTIND - 1))
 
 prereqs2 "$@"
diff --git a/.local/bin/flac2opus b/.local/bin/flac2opus
--- a/.local/bin/flac2opus
+++ b/.local/bin/flac2opus
@@ -19,14 +19,18 @@ set -e
 # functions are available. if not, exit due to potentially unpredictable
 # behavior.
 readonly library="${HOME}/.local/bin/common.sh"
+
 if [ -r "${library}" ]; then
   . "${library}"
+
 else
   cat >&2 <<EOF
 ${library} doesn't exist or isn't readable.
 ${0##*/} may not function correctly without it; exiting for safety.
 EOF
+
   exit 1
+
 fi
 
 check_deps <<'EOF'
@@ -34,5 +38,6 @@ opusenc
 parallel
 EOF
 
-parallel opusenc --bitrate 192 '{}' '{.}.opus' ::: ./*.flac \
-  || err 'Unable to convert from FLAC to opus.'
+if ! parallel opusenc --bitrate 192 '{}' '{.}.opus' ::: ./*.flac; then
+  err 'Unable to convert from FLAC to opus.'
+fi
diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -19,14 +19,18 @@ set -e
 # functions are available. if not, exit due to potentially unpredictable
 # behavior.
 readonly library="${HOME}/.local/bin/common.sh"
+
 if [ -r "${library}" ]; then
   . "${library}"
+
 else
   cat >&2 <<EOF
 ${library} doesn't exist or isn't readable.
 ${0##*/} may not function correctly without it; exiting for safety.
 EOF
+
   exit 1
+
 fi
 
 usage() {
@@ -39,17 +43,22 @@ ${0##*/} [cue file] [FLAC file]
 -c : convert 24bit flac to 16bit before splitting (sox needed)
 -d : delete the original FLAC file.
 EOF
+
   exit 1
+
 }
 
 # determines which executable name to use for cuetag.
 assign_cuetag() {
   if [ -x "$(command -v 'cuetag')" ]; then
     readonly cuetag='cuetag'
+
   elif [ -x "$(command -v 'cuetag.sh')" ]; then
     readonly cuetag='cuetag.sh'
+
   else
     err 'Neither cuetag nor cuetag.sh found.'
+
   fi
 }
 
@@ -58,25 +67,35 @@ assign_cuetag() {
 # $1 is a FLAC file to be converted.
 conv16() {
   staging_file="${1%.flac}-staging.flac"
+
   # http://sox.sourceforge.net/Docs/FAQ
   #
   # according to sox(1), most noise shaping filters are only available
   # at 44.1kHz, so that is the chosen sample rate.
   if sox "$1" -SGb 16 "${staging_file}" rate -v 44100 dither -s; then
     mv -- "${staging_file}" "$1"
+
   else
     err 'Failed to convert 24-bit FLAC file to 16-bit.'
+
   fi
+
 }
 
 splitflac() {
   [ -e "$2.bak" ] && err "$2.bak exists, exiting to prevent clobbering."
+
   # spaces in shnsplit filename messes up cue tagging, so just leave
   # the default in place. it's the only way to be sure that we won't run
   # into that issue, because %t will often add spaces too.
-  cuebreakpoints -- "$1" | shnsplit -o flac -- "$2" || err 'Unable to split the FLAC file.'
+  if ! { cuebreakpoints -- "$1" | shnsplit -o flac -- "$2"; }; then
+    err 'Unable to split the FLAC file.'
+  fi
+
   mv -- "$2" "$2.bak"
+
   "${cuetag}" "$1" ./*.flac || err 'Unable to tag FLAC files.'
+
   [ "${DELETE}" = 'yes' ] && rm -- "$2.bak"
 }
 
@@ -93,12 +112,15 @@ EOF
 readonly args_needed=2
 
 while getopts cd opt; do
+
   case "${opt}" in
     c) readonly CONVERT='yes' ;;
     d) readonly DELETE='yes'  ;;
     *) usage                  ;;
   esac
+
 done
+
 shift $((OPTIND - 1))
 
 [ "$#" = "${args_needed}" ] || usage
