beginning of indentation via spaces and alignment purge

diff --git a/.local/bin/filehandler b/.local/bin/filehandler
--- a/.local/bin/filehandler
+++ b/.local/bin/filehandler
@@ -18,13 +18,13 @@ set -e
 
 
 err() {
-    printf '%s\n' "$*" >&2
-    exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-    err "usage:
+	err "usage:
 ${0##*/} [options] [file]
 
 options:
@@ -45,78 +45,78 @@ ${0##*/} only processes the first operation it sees."
 
 
 menu() {
-    dmenu -i -fn 'mono-12'           \
-        -nb "${background:-#040516}" \
-        -nf "${color3:-#9974e7}"     \
-        -sb "${background:-#040516}" \
-        -sf "${foreground:-#e0cef3}" \
-        "$@"
+	dmenu -i -fn 'mono-12' \
+		-nb "${background:-#040516}" \
+		-nf "${color3:-#9974e7}" \
+		-sb "${background:-#040516}" \
+		-sf "${foreground:-#e0cef3}" \
+		"$@"
 }
 
 
 check_deps() {
-    while read -r dependency; do
+	while read -r dependency; do
 
-        [ -x "$(command -v -- "${dependency}")" ] \
-            || err "${dependency} not found in PATH or not executable."
+		[ -x "$(command -v -- "${dependency}")" ] \
+			|| err "${dependency} not found in PATH or not executable."
 
-    done
+	done
 }
 
 
 import_colors_sh() {
-    readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+	readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
 
-    if ! [ -r "${COLORS_SH}" ]; then
-        echo "${COLORS_SH} is not readable." >&2
+	if ! [ -r "${COLORS_SH}" ]; then
+		echo "${COLORS_SH} is not readable." >&2
 
-    elif ! [ -f "${COLORS_SH}" ]; then
-        echo "${COLORS_SH} is not a file." >&2
+	elif ! [ -f "${COLORS_SH}" ]; then
+		echo "${COLORS_SH} is not a file." >&2
 
-  # passed sanity checks, so source the file
-    else
-        . "${COLORS_SH}"
+	# passed sanity checks, so source the file
+	else
+		. "${COLORS_SH}"
 
-    fi
+	fi
 }
 
 
 # assigns a value to ${preload_dir} based on the file's mimetype.
 determine_preload_dir() {
-    MIMETYPE="$(file -ib -- "${FILE}")"
-    readonly MIMETYPE
+	MIMETYPE="$(file -ib -- "${FILE}")"
+	readonly MIMETYPE
 
-    case "${MIMETYPE}" in
-        # these are organized alphabetically by mimetype
-        application/epub*) readonly PRELOAD_DIR="${HOME}/books"          ;;
-        application/pdf*)  readonly PRELOAD_DIR="${HOME}/books"          ;;
-        image/vnd.djvu)    readonly PRELOAD_DIR="${HOME}/books"          ;;
-        image/*)           readonly PRELOAD_DIR="${HOME}/pics"           ;;
-        video/*)           readonly PRELOAD_DIR="${HOME}/videos"         ;;
-        *)                 err "No preload directory for this filetype." ;;
-    esac
+	case "${MIMETYPE}" in
+		# these are organized alphabetically by mimetype
+		application/epub*) readonly PRELOAD_DIR="${HOME}/books" ;;
+		application/pdf*) readonly PRELOAD_DIR="${HOME}/books" ;;
+		image/vnd.djvu) readonly PRELOAD_DIR="${HOME}/books" ;;
+		image/*) readonly PRELOAD_DIR="${HOME}/pics" ;;
+		video/*) readonly PRELOAD_DIR="${HOME}/videos" ;;
+		*) err "No preload directory for this filetype." ;;
+	esac
 }
 
 
 move_file() {
-    if mv -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
-        notify-send -- "${FILE##*/} moved to ${TILDE_DEST}"
+	if mv -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
+		notify-send -- "${FILE##*/} moved to ${TILDE_DEST}"
 
-    else
-        err "Failed to move ${FILE##*/}"
+	else
+		err "Failed to move ${FILE##*/}"
 
-    fi
+	fi
 }
 
 
 copy_file() {
-    if cp -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
-        notify-send -- "${FILE##*/} copied to ${TILDE_DEST}"
+	if cp -- "${FILE}" "${NO_TILDE_DEST}/${FILE##*/}"; then
+		notify-send -- "${FILE##*/} copied to ${TILDE_DEST}"
 
-    else
-        err "Failed to copy ${FILE##*/}"
+	else
+		err "Failed to copy ${FILE##*/}"
 
-    fi
+	fi
 }
 
 
@@ -124,38 +124,38 @@ copy_file() {
 # can be moved to. once the user chooses a destination with dmenu, move
 # the file there and send a notification.
 handle_dest() {
-    determine_preload_dir
+	determine_preload_dir
 
-    # substitutes $HOME with a tilde so the list of directories in dmenu is
-    # more readable.
-    TILDE_DEST="$(
-        { find "${PRELOAD_DIR}" -type d | sed -- "s|^${HOME}|~|g"
-            echo 'exit'
-        } | menu -l 10 -p "Where should ${FILE##*/} be placed?"
-    )"
+	# substitutes $HOME with a tilde so the list of directories in dmenu is
+	# more readable.
+	TILDE_DEST="$(
+		{ find "${PRELOAD_DIR}" -type d | sed -- "s|^${HOME}|~|g"
+			echo 'exit'
+		} | menu -l 10 -p "Where should ${FILE##*/} be placed?"
+	)"
 
-    readonly TILDE_DEST
-
-
-    case "${TILDE_DEST}" in
-
-        'exit')
-            exit 0
-
-            ;;
-
-        '')
-            err "${0##*/} needs a destination."
-
-            ;;
-
-    esac
+	readonly TILDE_DEST
 
 
-    NO_TILDE_DEST="$(echo "${TILDE_DEST}" | sed -- "s|^~|${HOME}|g")"
-    readonly NO_TILDE_DEST
+	case "${TILDE_DEST}" in
 
-    mkdir -p -- "${NO_TILDE_DEST}" || err "${TILDE_DEST} could not be created with mkdir(1)."
+		'exit')
+			exit 0
+
+			;;
+
+		'')
+			err "${0##*/} needs a destination."
+
+			;;
+
+	esac
+
+
+	NO_TILDE_DEST="$(echo "${TILDE_DEST}" | sed -- "s|^~|${HOME}|g")"
+	readonly NO_TILDE_DEST
+
+	mkdir -p -- "${NO_TILDE_DEST}" || err "${TILDE_DEST} could not be created with mkdir(1)."
 }
 
 
@@ -164,30 +164,30 @@ handle_dest() {
 #
 # dmenu seems to need at least one item from STDIN to behave properly.
 rename_file() {
-    NEW_FILENAME="$(echo 'exit' | menu -p "Rename ${FILE##*/} to what?")"
-    readonly NEW_FILENAME
+	NEW_FILENAME="$(echo 'exit' | menu -p "Rename ${FILE##*/} to what?")"
+	readonly NEW_FILENAME
 
-    case "${NEW_FILENAME}" in
+	case "${NEW_FILENAME}" in
 
-        'exit')
-            exit 0
+		'exit')
+			exit 0
 
-            ;;
+			;;
 
-        '')
-            err "${0##*/} needs a new name to rename ${FILE##*/} to."
+		'')
+			err "${0##*/} needs a new name to rename ${FILE##*/} to."
 
-            ;;
+			;;
 
-    esac
+	esac
 
-    if mv -- "${FILE}" "${FILE%/*}/${NEW_FILENAME}"; then
-        notify-send -- "${FILE##*/} renamed to ${NEW_FILENAME}"
+	if mv -- "${FILE}" "${FILE%/*}/${NEW_FILENAME}"; then
+		notify-send -- "${FILE##*/} renamed to ${NEW_FILENAME}"
 
-    else
-        err "Failed to rename ${FILE}."
+	else
+		err "Failed to rename ${FILE}."
 
-    fi
+	fi
 }
 
 
@@ -200,12 +200,12 @@ EOF
 
 while getopts chmn opt; do
 
-    case "${opt}" in
-        'c')     readonly OPERATION='copy'; break   ;;
-        'm')     readonly OPERATION='move'; break   ;;
-        'n')     readonly OPERATION='rename'; break ;;
-        'h'|*)   usage                              ;;
-    esac
+	case "${opt}" in
+		'c') readonly OPERATION='copy'; break ;;
+		'm') readonly OPERATION='move'; break ;;
+		'n') readonly OPERATION='rename'; break ;;
+		'h'|*) usage ;;
+	esac
 
 done
 
@@ -221,18 +221,18 @@ readonly FILE
 
 # if there is no operation, prompt the user to select one.
 if [ -z "${OPERATION}" ]; then
-    OPERATION="$(printf '%s\n' 'copy' 'move' 'rename' | menu -p "What to do with ${FILE}?")"
-    readonly OPERATION
+	OPERATION="$(printf '%s\n' 'copy' 'move' 'rename' | menu -p "What to do with ${FILE}?")"
+	readonly OPERATION
 
-    # a small delay needs to be here. without it, the subsequent menu
-    # won't appear sometimes.
-    sleep 0.25
+	# a small delay needs to be here. without it, the subsequent menu
+	# won't appear sometimes.
+	sleep 0.25
 fi
 
 
 case "${OPERATION}" in
-    'copy')   handle_dest && copy_file ;;
-    'move')   handle_dest && move_file ;;
-    'rename') rename_file              ;;
-    *)        usage                    ;;
+	'copy') handle_dest && copy_file ;;
+	'move') handle_dest && move_file ;;
+	'rename') rename_file ;;
+	*) usage ;;
 esac
diff --git a/.local/bin/linkhandler b/.local/bin/linkhandler
--- a/.local/bin/linkhandler
+++ b/.local/bin/linkhandler
@@ -18,60 +18,60 @@ set -e
 
 
 err() {
-    printf '%s\n' "$*" >&2
-    exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 check_deps() {
-    while read -r dependency; do
+	while read -r dependency; do
 
-        [ -x "$(command -v -- "${dependency}")" ] \
-            || err "${dependency} not found in PATH or not executable."
+		[ -x "$(command -v -- "${dependency}")" ] \
+			|| err "${dependency} not found in PATH or not executable."
 
-    done
+	done
 }
 
 
 import_colors_sh() {
-    readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
+	readonly COLORS_SH="${XDG_CACHE_HOME:=${HOME}/.cache}/wal/colors.sh"
 
-    if ! [ -r "${COLORS_SH}" ]; then
-        echo "${COLORS_SH} is not readable." >&2
+	if ! [ -r "${COLORS_SH}" ]; then
+		echo "${COLORS_SH} is not readable." >&2
 
-    elif ! [ -f "${COLORS_SH}" ]; then
-        echo "${COLORS_SH} is not a file." >&2
+	elif ! [ -f "${COLORS_SH}" ]; then
+		echo "${COLORS_SH} is not a file." >&2
 
-    # passed sanity checks, so source the file
-    else
-        . "${COLORS_SH}"
+	# passed sanity checks, so source the file
+	else
+		. "${COLORS_SH}"
 
-    fi
+	fi
 }
 
 
 menu() {
-    dmenu -i -fn 'mono-12'           \
-        -nb "${background:-#040516}" \
-        -nf "${color3:-#9974e7}"     \
-        -sb "${background:-#040516}" \
-        -sf "${foreground:-#e0cef3}" \
-        "$@"
+	dmenu -i -fn 'mono-12' \
+		-nb "${background:-#040516}" \
+		-nf "${color3:-#9974e7}" \
+		-sb "${background:-#040516}" \
+		-sf "${foreground:-#e0cef3}" \
+		"$@"
 }
 
 
 # if no arg is passed and STDIN is empty, exit with an error.
 check_opts() {
-    if [ -n "$1" ]; then
-        readonly URL="$1"
+	if [ -n "$1" ]; then
+		readonly URL="$1"
 
-    elif [ ! -t 0 ]; then
-        read -r URL && readonly URL
+	elif [ ! -t 0 ]; then
+		read -r URL && readonly URL
 
-    else
-        err "${0##*/} needs a URL!"
+	else
+		err "${0##*/} needs a URL!"
 
-    fi
+	fi
 }
 
 
@@ -80,97 +80,97 @@ check_opts() {
 # output is squelched for most options since I primarily use this with
 # newsboat.
 linkhandler() {
-    case "$(menu -l "${NUM_OF_OPTS}" -p 'What to do with this URL?')" in
+	case "$(menu -l "${NUM_OF_OPTS}" -p 'What to do with this URL?')" in
 
-        'copy duration')
-            DURATION="$(yt-dlp --get-duration -- "${URL}" 2>/dev/null)"
-            readonly DURATION
+		'copy duration')
+			DURATION="$(yt-dlp --get-duration -- "${URL}" 2>/dev/null)"
+			readonly DURATION
 
-            if [ -n "${DURATION}" ]; then
-                printf '%s' "${DURATION}" | xclip -selection clipboard
-                notify-send -- "Copied video duration (${DURATION})."
+			if [ -n "${DURATION}" ]; then
+				printf '%s' "${DURATION}" | xclip -selection clipboard
+				notify-send -- "Copied video duration (${DURATION})."
 
-            else
-                err 'Empty input, so no duration was yanked.'
+			else
+				err 'Empty input, so no duration was yanked.'
 
-            fi
+			fi
 
-            ;;
+			;;
 
-        'copy title')
-            TITLE="$(yt-dlp -e -- "${URL}" 2>/dev/null)"
-            readonly TITLE
+		'copy title')
+			TITLE="$(yt-dlp -e -- "${URL}" 2>/dev/null)"
+			readonly TITLE
 
-            if [ -n "${TITLE}" ]; then
-                printf '%s' "${TITLE}" | xclip -selection clipboard
-                notify-send -- "${TITLE} yanked."
+			if [ -n "${TITLE}" ]; then
+				printf '%s' "${TITLE}" | xclip -selection clipboard
+				notify-send -- "${TITLE} yanked."
 
-            else
-                err 'Empty input, so no title yanked.'
+			else
+				err 'Empty input, so no title yanked.'
 
-            fi
+			fi
 
-            ;;
+			;;
 
-        'download audio')
-            tmux new-window "yt-dlp -xf bestaudio/best -- ${URL}; read"
+		'download audio')
+			tmux new-window "yt-dlp -xf bestaudio/best -- ${URL}; read"
 
-            ;;
+			;;
 
-        'download file')
-            tmux new-window "(cd ${HOME}/Downloads && ftp -nU '' -- ${URL}); read"
+		'download file')
+			tmux new-window "(cd ${HOME}/Downloads && ftp -nU '' -- ${URL}); read"
 
-            ;;
+			;;
 
-        'download video')
-            tmux new-window "yt-dlp -- ${URL}; read"
+		'download video')
+			tmux new-window "yt-dlp -- ${URL}; read"
 
-            ;;
+			;;
 
-        'listen')
-            tmux new-window "mpva -- ${URL}"
+		'listen')
+			tmux new-window "mpva -- ${URL}"
 
-            ;;
+			;;
 
-        'print duration')
-            DURATION="$(yt-dlp --get-duration -- "${URL}" 2>/dev/null)"
+		'print duration')
+			DURATION="$(yt-dlp --get-duration -- "${URL}" 2>/dev/null)"
 
-            if [ -n "${DURATION}" ]; then
-                notify-send -- "${DURATION}"
+			if [ -n "${DURATION}" ]; then
+				notify-send -- "${DURATION}"
 
-            else
-                err 'Empty input, so no duration printed.'
+			else
+				err 'Empty input, so no duration printed.'
 
-            fi
+			fi
 
-            ;;
+			;;
 
-        'read')
-            tmux new-window "ftp -no - -U '' -- ${URL} | zathura -- -"
+		'read')
+			tmux new-window "ftp -no - -U '' -- ${URL} | zathura -- -"
 
-            ;;
+			;;
 
-        'view image')
-            viewimg "${URL}"
+		'view image')
+			viewimg "${URL}"
 
-            ;;
+			;;
 
-        'watch')
-            tmux new-window "mpv -- ${URL}"
+		'watch')
+			tmux new-window "mpv -- ${URL}"
 
-            ;;
+			;;
 
-        'watch (loop)')
-            tmux new-window "mpv --loop -- ${URL}"
+		'watch (loop)')
+			tmux new-window "mpv --loop -- ${URL}"
 
-        ;;
+			;;
 
-        *)
-            err "${0##*/} doesn't support that option."
+		*)
+			err "${0##*/} doesn't support that option."
 
-            ;;
+			;;
 
-    esac
+	esac
 }
 
 
diff --git a/.local/bin/ssg6 b/.local/bin/ssg6
--- a/.local/bin/ssg6
+++ b/.local/bin/ssg6
@@ -17,275 +17,275 @@
 set -e
 
 main() {
-    for pos_par in "$1" "$2" "$3" "$4"; do
-        [ -n "${pos_par}" ] || usage
-    done
+	for pos_par in "$1" "$2" "$3" "$4"; do
+		[ -n "${pos_par}" ] || usage
+	done
 
-    for pos_par in "$1" "$2"; do
-        [ -d "${pos_par}" ] || no_dir "${pos_par}"
-    done
+	for pos_par in "$1" "$2"; do
+		[ -d "${pos_par}" ] || no_dir "${pos_par}"
+	done
 
-    SRC="$(readlink_f "$1")"
-    readonly SRC
+	SRC="$(readlink_f "$1")"
+	readonly SRC
 
-    DST="$(readlink_f "$2")"
-    readonly DST
+	DST="$(readlink_f "$2")"
+	readonly DST
 
-    IGNORE="$(
-        if [ ! -f "${SRC}/.ssgignore" ]; then
-            printf ' ! -path "*/.*"'
-            return
-        fi
+	IGNORE="$(
+		if [ ! -f "${SRC}/.ssgignore" ]; then
+			printf ' ! -path "*/.*"'
+			return
+		fi
 
-        while read -r x; do
-            [ -n "${x}" ] || continue
-            printf ' ! -path "*/%s*"' "${x}"
-        done < "${SRC}/.ssgignore"
-    )"
-    readonly IGNORE
+		while read -r x; do
+			[ -n "${x}" ] || continue
+			printf ' ! -path "*/%s*"' "${x}"
+		done < "${SRC}/.ssgignore"
+	)"
+	readonly IGNORE
 
-    # files
+	# files
 
-    title="$3"
+	title="$3"
 
-    readonly H_FILE="${SRC}/_header.html"
-    readonly F_FILE="${SRC}/_footer.html"
-    if [ -f "${F_FILE}" ]; then
-        FOOTER="$(cat -- "${F_FILE}")" && readonly FOOTER && export FOOTER
-    fi
+	readonly H_FILE="${SRC}/_header.html"
+	readonly F_FILE="${SRC}/_footer.html"
+	if [ -f "${F_FILE}" ]; then
+		FOOTER="$(cat -- "${F_FILE}")" && readonly FOOTER && export FOOTER
+	fi
 
-    if [ -f "${H_FILE}" ]; then
-        HEADER="$(cat -- "${H_FILE}")" && readonly HEADER && export HEADER
-    fi
+	if [ -f "${H_FILE}" ]; then
+		HEADER="$(cat -- "${H_FILE}")" && readonly HEADER && export HEADER
+	fi
 
-    list_dirs "${SRC}" | (cd "${SRC}" && cpio -pdu -- "${DST}")
+	list_dirs "${SRC}" | (cd "${SRC}" && cpio -pdu -- "${DST}")
 
-    fs="$(
-        if [ -f "${DST}/.files" ]; then
-            list_affected_files "${SRC}" "${DST}/.files"
+	fs="$(
+		if [ -f "${DST}/.files" ]; then
+			list_affected_files "${SRC}" "${DST}/.files"
 
-        else
-            list_files "$1"
+		else
+			list_files "$1"
 
-        fi
-    )"
+		fi
+	)"
 
-    if [ -n "${fs}" ]; then
-        echo "${fs}" | tee -- "${DST}/.files"
+	if [ -n "${fs}" ]; then
+		echo "${fs}" | tee -- "${DST}/.files"
 
-        if echo "${fs}" | grep -q '\.md$'; then
+		if echo "${fs}" | grep -q '\.md$'; then
 
-            if [ -x "$(command -v -- 'lowdown')" ]; then
-                echo "${fs}" \
-                    | grep '\.md$' \
-                    | render_md_files_lowdown "${SRC}" "${DST}" "${title}"
+			if [ -x "$(command -v -- 'lowdown')" ]; then
+				echo "${fs}" \
+					| grep '\.md$' \
+					| render_md_files_lowdown "${SRC}" "${DST}" "${title}"
 
-            elif [ -x "$(command -v -- 'Markdown.pl')" ]; then
-                echo "${fs}" \
-                    | grep '\.md$' \
-                    | render_md_files_Markdown_pl "${SRC}" "${DST}" "${title}"
+			elif [ -x "$(command -v -- 'Markdown.pl')" ]; then
+				echo "${fs}" \
+					| grep '\.md$' \
+					| render_md_files_Markdown_pl "${SRC}" "${DST}" "${title}"
 
-            else
-                echo "couldn't find lowdown nor Markdown.pl"
-                exit 3
+			else
+				echo "couldn't find lowdown nor Markdown.pl"
+				exit 3
 
-            fi
+			fi
 
-        fi
+		fi
 
-        echo "${fs}" \
-            | grep '\.html$' \
-            | render_html_files "${SRC}" "${DST}" "${title}"
+		echo "${fs}" \
+			| grep '\.html$' \
+			| render_html_files "${SRC}" "${DST}" "${title}"
 
-        echo "${fs}" \
-            | grep -Ev '\.md$|\.html$' \
-            | (cd "${SRC}" && cpio -pu -- "${DST}")
+		echo "${fs}" \
+			| grep -Ev '\.md$|\.html$' \
+			| (cd "${SRC}" && cpio -pu -- "${DST}")
 
-    fi
+	fi
 
-    printf '[ssg] ' >&2
-    print_status 'file, ' 'files, ' "${fs}" >&2
+	printf '[ssg] ' >&2
+	print_status 'file, ' 'files, ' "${fs}" >&2
 
 
-    # sitemap
+	# sitemap
 
-    base_url="$4"
-    date="$(date '+%F')"
-    urls="$(list_pages "${SRC}")"
+	base_url="$4"
+	date="$(date '+%F')"
+	urls="$(list_pages "${SRC}")"
 
-    [ -n "${urls}" ] \
-        && render_sitemap "${urls}" "${base_url}" "${date}" > "${DST}/sitemap.xml"
+	[ -n "${urls}" ] \
+		&& render_sitemap "${urls}" "${base_url}" "${date}" > "${DST}/sitemap.xml"
 
-    print_status 'url' 'urls' "${urls}" >&2
-    echo >&2
+	print_status 'url' 'urls' "${urls}" >&2
+	echo >&2
 }
 
 
 readlink_f() {
-    file="$1"
-    cd "${file%/*}"
-    file="${file##*/}"
+	file="$1"
+	cd "${file%/*}"
+	file="${file##*/}"
 
-    while [ -L "${file}" ]; do
-        file="$(readlink -- "${file}")"
-        cd "${file%/*}"
-        file="${file##*/}"
-    done
+	while [ -L "${file}" ]; do
+		file="$(readlink -- "${file}")"
+		cd "${file%/*}"
+		file="${file##*/}"
+	done
 
-    dir="$(pwd -P)"
-    echo "${dir}/${file}"
+	dir="$(pwd -P)"
+	echo "${dir}/${file}"
 }
 
 
 print_status() {
-    [ -z "$3" ] && printf 'no %s' "$2" && return
+	[ -z "$3" ] && printf 'no %s' "$2" && return
 
-    echo "$3" | awk -v singular="$1" -v plural="$2" -- '
-    END {
-        if (NR==1) printf NR " " singular
-        if (NR>1) printf NR " " plural
-    }'
+	echo "$3" | awk -v singular="$1" -v plural="$2" -- '
+	END {
+		if (NR==1) printf NR " " singular
+		if (NR>1) printf NR " " plural
+	}'
 }
 
 
 usage() {
-    echo "usage: ${0##*/} src dst title base_url" >&2
-    exit 1
+	echo "usage: ${0##*/} src dst title base_url" >&2
+	exit 1
 }
 
 
 no_dir() {
-    echo "${0##*/}: $1: No such directory" >&2
-    exit 2
+	echo "${0##*/}: $1: No such directory" >&2
+	exit 2
 }
 
 
 list_dirs() {
-    cd "$1" && eval "find . -type d ! -name '.' ! -path '*/_*' ${IGNORE}"
+	cd "$1" && eval "find . -type d ! -name '.' ! -path '*/_*' ${IGNORE}"
 }
 
 
 list_files() {
-    cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' ${IGNORE}"
+	cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' ${IGNORE}"
 }
 
 
 list_dependent_files() {
-    e="\\( -name '*.html' -o -name '*.md' -o -name '*.css' -o -name '*.js' \\)"
-    cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' ${IGNORE} ${e}"
+	e="\\( -name '*.html' -o -name '*.md' -o -name '*.css' -o -name '*.js' \\)"
+	cd "$1" && eval "find . -type f ! -name '.' ! -path '*/_*' ${IGNORE} ${e}"
 }
 
 
 list_newer_files() {
-    cd "$1" && eval "find . -type f ! -name '.' ${IGNORE} -newer $2"
+	cd "$1" && eval "find . -type f ! -name '.' ${IGNORE} -newer $2"
 }
 
 
 has_partials() {
-    grep -qE -- '^./_.*\.html$|^./_.*\.js$|^./_.*\.css$'
+	grep -qE -- '^./_.*\.html$|^./_.*\.js$|^./_.*\.css$'
 }
 
 
 list_affected_files() {
-    fs="$(list_newer_files "$1" "$2")"
+	fs="$(list_newer_files "$1" "$2")"
 
-    if echo "${fs}" | has_partials; then
-        list_dependent_files "$1"
+	if echo "${fs}" | has_partials; then
+		list_dependent_files "$1"
 
-    else
-        echo "${fs}"
+	else
+		echo "${fs}"
 
-    fi
+	fi
 }
 
 
 render_html_files() {
-    while read -r f; do
-        render_html_file "$3" < "$1/${f}" > "$2/${f}"
+	while read -r f; do
+		render_html_file "$3" < "$1/${f}" > "$2/${f}"
 
-    done
+	done
 }
 
 
 render_md_files_lowdown() {
-    while read -r f; do
+	while read -r f; do
 
-        lowdown                     \
-            --html-no-escapehtml    \
-            --html-no-skiphtml      \
-            --parse-no-metadata     \
-            --parse-no-autolink     \
-            -- "$1/${f}"            \
-            | render_html_file "$3" \
-            > "$2/${f%\.md}.html"
+		lowdown \
+			--html-no-escapehtml \
+			--html-no-skiphtml \
+			--parse-no-metadata \
+			--parse-no-autolink \
+			-- "$1/${f}" \
+			| render_html_file "$3" \
+			> "$2/${f%\.md}.html"
 
-    done
+	done
 }
 
 
 render_md_files_Markdown_pl() {
-    while read -r f; do
+	while read -r f; do
 
-        Markdown.pl -- "$1/${f}"    \
-            | render_html_file "$3" \
-            > "$2/${f%\.md}.html"
+		Markdown.pl -- "$1/${f}" \
+			| render_html_file "$3" \
+			> "$2/${f%\.md}.html"
 
-    done
+	done
 }
 
 
 render_html_file() {
-    # h/t Devin Teske
-    awk -v title="$1" -- '
-    { body = body "\n" $0 }
-    END {
-        body = substr(body, 2)
-        if (body ~ /<[/]?[Hh][Tt][Mm][Ll]/) {
-            print body
-            exit
-        }
-        if (match(body, /<[[:space:]]*[Hh]1(>|[[:space:]][^>]*>)/)) {
-            t = substr(body, RSTART + RLENGTH)
-            sub("<[[:space:]]*/[[:space:]]*[Hh]1.*", "", t)
-            gsub(/^[[:space:]]*|[[:space:]]$/, "", t)
-            if (t) title = t " &mdash; " title
-        }
-        n = split(ENVIRON["HEADER"], header, /\n/)
-        for (i = 1; i <= n; i++) {
-            if (match(tolower(header[i]), "<title></title>")) {
-                head = substr(header[i], 1, RSTART - 1)
-                tail = substr(header[i], RSTART + RLENGTH)
-                print head "<title>" title "</title>" tail
-            } else print header[i]
-        }
-        print body
-        print ENVIRON["FOOTER"]
-    }'
+	# h/t Devin Teske
+	awk -v title="$1" -- '
+	{ body = body "\n" $0 }
+	END {
+		body = substr(body, 2)
+		if (body ~ /<[/]?[Hh][Tt][Mm][Ll]/) {
+			print body
+			exit
+		}
+		if (match(body, /<[[:space:]]*[Hh]1(>|[[:space:]][^>]*>)/)) {
+			t = substr(body, RSTART + RLENGTH)
+			sub("<[[:space:]]*/[[:space:]]*[Hh]1.*", "", t)
+			gsub(/^[[:space:]]*|[[:space:]]$/, "", t)
+			if (t) title = t " &mdash; " title
+		}
+		n = split(ENVIRON["HEADER"], header, /\n/)
+		for (i = 1; i <= n; i++) {
+			if (match(tolower(header[i]), "<title></title>")) {
+				head = substr(header[i], 1, RSTART - 1)
+				tail = substr(header[i], RSTART + RLENGTH)
+				print head "<title>" title "</title>" tail
+			} else print header[i]
+		}
+		print body
+		print ENVIRON["FOOTER"]
+	}'
 }
 
 
 list_pages() {
-    e="\\( -name '*.html' -o -name '*.md' \\)"
-    cd "$1" \
-        && eval "find . -type f ! -path '*/.*' ! -path '*/_*' ${IGNORE} ${e}" \
-        | sed -- 's#^./##;s#.md$#.html#;s#/index.html$#/#'
+	e="\\( -name '*.html' -o -name '*.md' \\)"
+	cd "$1" \
+		&& eval "find . -type f ! -path '*/.*' ! -path '*/_*' ${IGNORE} ${e}" \
+		| sed -- 's#^./##;s#.md$#.html#;s#/index.html$#/#'
 }
 
 
 render_sitemap() {
-    urls="$1"
-    base_url="$2"
-    date="$3"
+	urls="$1"
+	base_url="$2"
+	date="$3"
 
-    echo '<?xml version="1.0" encoding="UTF-8"?>
+	echo '<?xml version="1.0" encoding="UTF-8"?>
 <urlset
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"
 xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
-    echo "${urls}" | sed -E -- 's#^(.*)$#<url><loc>'"${base_url}"'/\1</loc><lastmod>'\
+	echo "${urls}" | sed -E -- 's#^(.*)$#<url><loc>'"${base_url}"'/\1</loc><lastmod>'\
 "${date}"'</lastmod><priority>1.0</priority></url>#'
-    echo '</urlset>'
+	echo '</urlset>'
 }
 
 
diff --git a/.local/bin/volman b/.local/bin/volman
--- a/.local/bin/volman
+++ b/.local/bin/volman
@@ -16,72 +16,72 @@
 
 
 err() {
-    printf '%s\n' "$*" >&2
-    exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-    err "usage:
+	err "usage:
 ${0##*/} [inc|dec|mute]"
 }
 
 
 check_deps() {
-    while read -r dependency; do
+	while read -r dependency; do
 
-        [ -x "$(command -v -- "${dependency}")" ] \
-            || err "${dependency} not found in PATH or not executable."
+		[ -x "$(command -v -- "${dependency}")" ] \
+			|| err "${dependency} not found in PATH or not executable."
 
-    done
+	done
 }
 
 
 # either increase, decrease, or mute the volume if the appropriate
 # argument is given. if not, error and display usage details.
 adjust_vol() {
-    case "$1" in
-        'inc')  check_mute || sndioctl output.level=+0.05 >/dev/null 2>&1 ;;
-        'dec')  check_mute || sndioctl output.level=-0.05 >/dev/null 2>&1 ;;
-        'mute') sndioctl output.mute=! >/dev/null 2>&1                    ;;
-        *)      usage                                                     ;;
-    esac
+	case "$1" in
+		'inc') check_mute || sndioctl output.level=+0.05 >/dev/null 2>&1 ;;
+		'dec') check_mute || sndioctl output.level=-0.05 >/dev/null 2>&1 ;;
+		'mute') sndioctl output.mute=! >/dev/null 2>&1 ;;
+		*) usage ;;
+	esac
 }
 
 
 print_vol() {
-    if [ "${MUTED}" = 'true' ]; then
-        echo 'MUTED'
+	if [ "${MUTED}" = 'true' ]; then
+		echo 'MUTED'
 
-    else
-        echo "$@"
+	else
+		echo "$@"
 
-    fi
+	fi
 }
 
 
 # if muted, succeed.
 # if not muted, fail.
 check_mute() {
-    case "$(sndioctl -n output.mute 2>/dev/null)" in
-        1) return 0                                            ;;
-        0) return 1                                            ;;
-        *) err 'Failed to check output.mute with sndioctl(1).' ;;
-    esac
+	case "$(sndioctl -n output.mute 2>/dev/null)" in
+		1) return 0 ;;
+		0) return 1 ;;
+		*) err 'Failed to check output.mute with sndioctl(1).' ;;
+	esac
 }
 
 
 # get raw output level and convert it to something more parsable.
 get_vol() {
-    RAW_VOL="$(sndioctl -n output.level 2>/dev/null)"
-    readonly RAW_VOL
+	RAW_VOL="$(sndioctl -n output.level 2>/dev/null)"
+	readonly RAW_VOL
 
-    case "${RAW_VOL}" in
-        1.000) echo 100                                                  ;;
-        0.000) echo 0                                                    ;;
-               # division is here to truncate the floating point number.
-        *)     printf 'scale=0; (%.2g * %s) / 1\n' "${RAW_VOL}" 100 | bc ;;
-    esac
+	case "${RAW_VOL}" in
+		1.000) echo 100 ;;
+		0.000) echo 0 ;;
+		# division is here to truncate the floating point number.
+		*) printf 'scale=0; (%.2g * %s) / 1\n' "${RAW_VOL}" 100 | bc ;;
+	esac
 }
 
 
