.local/bin/flac2opus: remove dependency on common.sh

diff --git a/.local/bin/flac2opus b/.local/bin/flac2opus
--- a/.local/bin/flac2opus
+++ b/.local/bin/flac2opus
@@ -16,20 +16,27 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
+}
 
-fi
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
+
 
 check_deps <<'EOF'
 opusenc
