various:
1) functions condensed into one-liners where applicable

2) unnecessary imports removed

diff --git a/.local/bin/flac2opus b/.local/bin/flac2opus
--- a/.local/bin/flac2opus
+++ b/.local/bin/flac2opus
@@ -15,23 +15,6 @@ set -e
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-# check that the library file is readable. if it is, source it so its
-# functions are available. if not, exit due to potentially unpredictable
-# behavior.
-library="${HOME}/.local/bin/common.sh"
-if [ -r "${library}" ]; then
-  . "${library}"
-else
-  cat >&2 <<EOF
-${library} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it; exiting for safety.
-EOF
-  exit 1
-fi
-
 # encodes all flac files in ${PWD} to opus with parallelization
-main() {
-  parallel opusenc --bitrate 192 '{}' '{.}.opus' ::: ./*.flac
-}
-
-main || err 'Unable to convert files properly.'
+main() { parallel opusenc --bitrate 192 '{}' '{.}.opus' ::: ./*.flac; }
+main || echo 'Unable to convert files properly.' >&2; exit 1
diff --git a/.local/bin/randman b/.local/bin/randman
--- a/.local/bin/randman
+++ b/.local/bin/randman
@@ -1,5 +1,4 @@
 #!/usr/bin/env sh
-# shellcheck disable=SC1090
 set -e
 # Copyright (c) 2020-2021 Ashlen <eurydice@riseup.net>
 
@@ -15,30 +14,7 @@ set -e
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-# check that the library file is readable. if it is, source it so its
-# functions are available. if not, exit due to potentially unpredictable
-# behavior.
-library="${HOME}/.local/bin/common.sh"
-if [ -r "${library}" ]; then
-  . "${library}"
-else
-  cat >&2 <<EOF
-${library} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it; exiting for safety.
-EOF
-  exit 1
-fi
-
 # lists man page paths from listed sections, shuffles them, and returns
 # the first page (like drawing the top card from a shuffled deck).
-randman() {
-  man -w -S "$(uname -m)" -k sec~^1\|5\|6\|7\|8$ \
-    | sort -R \
-    | head -1
-}
-
-main() {
-  man "$(randman)" || err 'Unable to pick a random man page.'
-}
-
-main
+main() { man -w -k sec~^1\|5\|6\|7\|8$ | sort -R | head -1; }
+main || echo 'Unable to retrieve random man(1) page.' >&2; exit 1
