.local/bin/fzf-open: removes dependency on common.sh

diff --git a/.local/bin/fzf-open b/.local/bin/fzf-open
--- a/.local/bin/fzf-open
+++ b/.local/bin/fzf-open
@@ -16,26 +16,15 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
-
-fi
+}
 
 
 usage() {
   cat >&2 <<EOF
-${0##*/} requires ${args_needed} argument(s).
-
 usage:
 ${0##*/} [command] [dir for fzf]
 EOF
@@ -44,21 +33,44 @@ EOF
 }
 
 
-prereqs() {
-  readonly args_needed=2
-  [ "$#" -eq "${args_needed}" ] || usage
+check_deps() {
+  while read -r dependency; do
 
-  check_deps <<EOF
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
+
+
+args_needed() {
+  case "$1" in
+
+    ''|*[!0-9]*)
+      err "args_needed() needs a number."
+
+      ;;
+
+  esac
+
+  err "$1 argument(s) required."
+}
+
+
+[ "$#" -eq 2 ] || args_needed 2
+
+check_deps <<EOF
 fzf
 $1
 EOF
 
-  [ -r "$2" ] || err "$2 is not readable."
-  [ -d "$2" ] || err "$2 is not a directory."
-}
-
-
-prereqs "$@"
+[ -r "$2" ] || err "$2 is not readable."
+[ -d "$2" ] || err "$2 is not a directory."
 
 chosen_file="$( (cd "$2" && fzf) )"
 readonly chosen_file
