fix usage(), cleanup fzf-open

diff --git a/.local/bin/fzf-open b/.local/bin/fzf-open
--- a/.local/bin/fzf-open
+++ b/.local/bin/fzf-open
@@ -15,37 +15,35 @@
 
 set -e
 
-
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
 }
 
-
 usage() {
-	err "usage:
+	cat >&2 <<EOF
+usage:
 ${0##*/} [command] [dir for fzf]"
-}
-
-
-check_deps() {
-	while read -r dependency; do
-
-		[ -x "$(command -v -- "${dependency}")" ] \
-			|| err "${dependency} not found in PATH or not executable."
-
-	done
-}
-
-[ -z "$1" ] && usage
-[ -z "$2" ] && usage
-
-check_deps <<-EOF
-	fzf
-	$1
 EOF
+	exit 1
+}
+
+
+[ -n "$1" ] || usage
+[ -n "$2" ] || usage
+
+
+readonly DEPENDENCIES="fzf
+$1"
+
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
+done
+
 
 cd "$2" || err "Could not change directory to $2"
+
 
 CHOSEN_FILE="$(fzf)"
 readonly CHOSEN_FILE
@@ -54,6 +52,6 @@ FULL_PATH_OF_FILE="$(readlink -f -- "$2/${CHOSEN_FILE}")"
 readonly FULL_PATH_OF_FILE
 
 [ -n "${FULL_PATH_OF_FILE}" ] || err 'A file must be chosen.'
-[ -r "${FULL_PATH_OF_FILE}" ] || err 'File not readable.'
 
-"$1" "${FULL_PATH_OF_FILE}"
+
+exec "$1" -- "${FULL_PATH_OF_FILE}"
