genblock: gen_domains function

diff --git a/.local/bin/genblock b/.local/bin/genblock
--- a/.local/bin/genblock
+++ b/.local/bin/genblock
@@ -16,11 +16,19 @@
 set -e
 . "${HOME}/.local/bin/common.sh"
 
+tmpdir=$(mktemp -d /tmp/genblock.XXXXXX)
+blocklist="/etc/blocklist.txt"
 firebog=$(ftp -Vo - https://v.firebog.net/hosts/lists.php?type=tick)
-tmpdir=$(mktemp -d)
 raw_blocklist="${tmpdir}/raw_blocklist.txt"
 tmp_blocklist="${tmpdir}/blocklist.txt"
-blocklist="/etc/blocklist.txt"
+
+# TODO:
+# use less temporary files
+
+# if a blocklist has been retrieved recently, use it instead of
+# downloading a new one
+
+# have each function return values, and redirect output in main()
 
 backup() {
   if [ -f "${blocklist}" ]; then
@@ -34,30 +42,30 @@ dl_blocklist() {
   done
 }
 
-format_blocklist() {
+gen_domains() {
+  grep -v " localhost" "${raw_blocklist}" | \
+  (
+  grep -E '^0.0.0.0'
+  grep -E '^127.0.0.1'
+  )
+}
+
+format_domains() {
   case "${dns}" in
     "unwind")
       (
-      grep -E '^0.0.0.0' "${raw_blocklist}" \
-        | awk '$1 == "0.0.0.0" {print $2}'
-
-      grep -E '^127.0.0.1' "${raw_blocklist}" \
-        | grep -v "localhost" \
-        | awk '$1 == "127.0.0.1" {print $2}'
-
+      awk '$1 == "0.0.0.0" {print $2}' -
+      awk '$1 == "127.0.0.1" {print $2}' -
       # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
       printf "%s\\n" 'use-application-dns.net'
       )
       ;;
     "unbound")
       (
-      grep -E '^0.0.0.0' "${raw_blocklist}" \
-        | awk '$1 == "0.0.0.0" {print "local-zone: \""$2"\" always_refuse"}'
-
-      grep -E '^127.0.0.1' "${raw_blocklist}" \
-        | grep -v "localhost" \
-        | awk '$1 == "127.0.0.1" {print "local-zone: \""$2"\" always_refuse"}'
-
+      awk '$1 == "0.0.0.0" {print "local-zone: \""$2"\" always_refuse"}' \
+        -
+      awk '$1 == "127.0.0.1" {print "local-zone: \""$2"\" always_refuse"}' \
+        -
       # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
       printf "%s\\n" 'local-zone: "use-application-dns.net" always_refuse'
       )
@@ -66,7 +74,7 @@ format_blocklist() {
       | sed 's///g' \
       | sort \
       | uniq \
-      >> "${tmp_blocklist}"
+      > "${tmp_blocklist}"
     # the sed expression gets rid of the '^M' control character in
     # blocklists
 
@@ -125,7 +133,7 @@ main() {
     err "Only unwind(8) and unbound(8) are supported. Enable one of them and try again."
   fi
   dl_blocklist || err "Unable to download lists from firebog.net."
-  format_blocklist || err "Unable to format blocklist."
+  gen_domains | format_domains || err "Unable to format blocklist."
   backup || err "Unable to backup blocklist file."
   install_blocklist || err "Unable to install blocklist."
   restart_dns || err "Unable to restart DNS."
