various: the aim is to not use double quotes where single quotes would suffice

diff --git a/.local/bin/genblock b/.local/bin/genblock
--- a/.local/bin/genblock
+++ b/.local/bin/genblock
@@ -25,7 +25,7 @@ EOF
   exit 1
 fi
 
-blocklist="/etc/blocklist.txt"
+blocklist='/etc/blocklist.txt'
 firebog="$(ftp -Vo - https://v.firebog.net/hosts/lists.php?type=tick)"
 tmp_blocklist="$(mktemp /tmp/genblock.XXXXXX)"
 
@@ -45,28 +45,28 @@ dl_blocklists() {
 }
 
 grab_domains() {
-  grep -Ev "localhost$" "$1" \
+  grep -Ev 'localhost$' "$1" \
     | grep -E -e '^0.0.0.0' -e '^127.0.0.1'
 }
 
 format_domains() {
   case "${dns}" in
-    "unwind")
+    'unwind')
       (
       awk '$1 == "0.0.0.0" {print $2}' "$1"
       awk '$1 == "127.0.0.1" {print $2}' "$1"
       # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
-      printf "%s\\n" 'use-application-dns.net'
+      printf '%s' 'use-application-dns.net'
       )
       ;;
-    "unbound")
+    'unbound')
       (
       awk '$1 == "0.0.0.0" {print "local-zone: \""$2"\" always_refuse"}' \
         "$1"
       awk '$1 == "127.0.0.1" {print "local-zone: \""$2"\" always_refuse"}' \
         "$1"
       # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
-      printf "%s\\n" 'local-zone: "use-application-dns.net" always_refuse'
+      printf '%s' 'local-zone: "use-application-dns.net" always_refuse'
       )
       ;;
   esac \
@@ -89,11 +89,11 @@ EOF
 
 restart_dns() {
   case "${dns}" in
-    "unwind")
+    'unwind')
       unwind -n >/dev/null 2>&1 \
         && priv rcctl restart unwind >/dev/null 2>&1
       ;;
-    "unbound")
+    'unbound')
       unbound-checkconf >/dev/null 2>&1 \
         && priv rcctl restart unbound >/dev/null 2>&1
       ;;
@@ -117,20 +117,20 @@ rm_tmpfile() {
 }
 
 main() {
-  if rcctl ls on 2>/dev/null | grep -qE "^unwind$"; then
-    dns="unwind"
-  elif rcctl ls on 2>/dev/null | grep -qE "^unbound$"; then
-    dns="unbound"
+  if rcctl ls on 2>/dev/null | grep -qE '^unwind$'; then
+    dns='unwind'
+  elif rcctl ls on 2>/dev/null | grep -qE '^unbound$'; then
+    dns='unbound'
   else
-    err "Only unwind(8) and unbound(8) are supported. Enable one of them and try again."
+    err 'Only unwind(8) and unbound(8) are supported. Enable one of them and try again.'
   fi
   dl_blocklists \
     | grab_domains - \
     | format_domains - \
     > "${tmp_blocklist}" \
-    || err "Unable to create blocklist."
-  backup || err "Unable to backup blocklist file."
-  install_blocklist || err "Unable to install blocklist."
+    || err 'Unable to create blocklist.'
+  backup || err 'Unable to backup blocklist file.'
+  install_blocklist || err 'Unable to install blocklist.'
   restart_dns || revert
   rm_tmpfile || err "Unable to remove ${tmp_blocklist}."
 }
