genblock: separate functions for restarting unwind(8) and unbound(8)

diff --git a/.local/bin/genblock b/.local/bin/genblock
--- a/.local/bin/genblock
+++ b/.local/bin/genblock
@@ -84,13 +84,28 @@ chmod 0444 "${blocklist}"
 EOF
 }
 
-restart_dns() {
+restart_unwind() {
   # since the script checks to see which of these two is enabled in
-  # main(), there's no need for a check here. instead, the script checks
+  # main(), there's no need for a check here. instead, this function checks
   # that the configuration is sane.
   if unwind -n >/dev/null 2>&1; then
     priv rcctl restart unwind >/dev/null 2>&1
-  elif unbound-checkconf >/dev/null 2>&1; then
+  elif [ -f "${blocklist}.bak" ]; then
+    priv mv "${blocklist}.bak" "${blocklist}"
+  else
+    priv /usr/bin/env sh <<EOF
+rm "${blocklist}"
+touch "${blocklist}"
+chmod 0444 "${blocklist}"
+EOF
+  fi
+}
+
+restart_unbound() {
+  # since the script checks to see which of these two is enabled in
+  # main(), there's no need for a check here. instead, this function checks
+  # that the configuration is sane.
+  if unbound-checkconf >/dev/null 2>&1; then
     priv rcctl restart unbound >/dev/null 2>&1
   elif [ -f "${blocklist}.bak" ]; then
     priv mv "${blocklist}.bak" "${blocklist}"
@@ -112,13 +127,15 @@ main() {
   backup || err "Unable to backup blocklist file."
   if rcctl ls on 2>/dev/null | grep -qE "^unwind$"; then
     format_blocklist_unwind || err "Unable to format blocklist."
+    install_blocklist || err "Unable to install blocklist."
+    restart_unwind || err "Unable to restart unwind(8)."
   elif rcctl ls on 2>/dev/null | grep -qE "^unbound$"; then
     format_blocklist_unbound || err "Unable to format blocklist."
+    install_blocklist || err "Unable to install blocklist."
+    restart_unbound || err "Unable to restart unbound(8)."
   else
     err "Only unwind(8) and unbound(8) are supported. Enable one of these."
   fi
-  install_blocklist || err "Unable to install blocklist."
-  restart_dns || err "Unable to restart DNS."
   rm_tmpdir || err "Unable to remove ${tmpdir}."
 }
 
