cleanup genfavi and launch-element-web

diff --git a/.local/bin/genfavi b/.local/bin/genfavi
--- a/.local/bin/genfavi
+++ b/.local/bin/genfavi
@@ -15,18 +15,20 @@
 
 set -e
 
+readonly PROGRAM_NAME="${0##*/}"
 
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
 }
 
-
 usage() {
-	err "usage:
-${0##*/} [image]"
+	cat >&2 <<EOF
+usage:
+${PROGRAM_NAME} [image]
+EOF
+	exit 1
 }
-
 
 genfavi() {
 	convert "$1" -background white \
@@ -38,19 +40,16 @@ genfavi() {
 }
 
 
-[ -x "$(command -v 'convert')" ] || err "convert not found in PATH or not executable."
+command -v 'convert' >/dev/null 2>&1 || err 'convert not found in PATH.'
 
-[ -z "$1" ] && usage
+[ -n "$1" ] || usage
 
 case "$(file -ib -- "$1")" in
 	image/*) : ;; # images are OK to process
 	*) err "$1 isn't an image." ;;
 esac
 
-if genfavi "$1"; then
-	cp 'favicon.ico' 'favicon.png'
 
-else
-	err 'Unable to generate favicon.'
+genfavi "$1" && exec cp 'favicon.ico' 'favicon.png'
 
-fi
+err 'Unable to generate favicon.'
diff --git a/.local/bin/launch-element-web b/.local/bin/launch-element-web
--- a/.local/bin/launch-element-web
+++ b/.local/bin/launch-element-web
@@ -13,29 +13,13 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-
-# simple script to update element-web when we try to launch it.
+# Simple script to update element-web when we try to launch it.
 
 set -e
 
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
-}
-
-
-check_deps() {
-	while read -r dependency; do
-
-		[ -x "$(command -v -- "${dependency}")" ] \
-			|| err "${dependency} not found in PATH or not executable."
-
-	done
-}
-
-
-launch_browser() {
-	"${BROWSER}" -P "${BROWSER_PROFILE}" "${MATRIX_URI}"
 }
 
 
@@ -46,18 +30,21 @@ launch_browser() {
 : "${HANDLER:=${XDG_BIN_HOME}/handle-element-web.pl}"
 
 
-check_deps <<-EOF
-	${BROWSER}
-	${HANDLER}
-EOF
+readonly DEPENDENCIES="notify-send
+${BROWSER}
+${HANDLER}"
+
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
+done
+
+
+[ -n "${DISPLAY}" ] || err "${0##*/} needs a graphical environment."
 
 
 # automatically check for a new version of element-web and update if a
 # new version is found.
-if "${HANDLER}"; then
-	[ -n "${DISPLAY}" ] \
-		&& [ -x "$(command -v 'notify-send')" ] \
-		&& notify-send 'element-web updated'
-fi
+"${HANDLER}" && notify-send 'element-web updated'
 
-launch_browser
+exec "${BROWSER}" -P "${BROWSER_PROFILE}" "${MATRIX_URI}"
