rearrange

diff --git a/.local/bin/linkhandler b/.local/bin/linkhandler
--- a/.local/bin/linkhandler
+++ b/.local/bin/linkhandler
@@ -23,6 +23,16 @@ err() {
 	exit 1
 }
 
+
+if [ -n "$1" ]; then
+	readonly URL="$1"
+elif [ ! -t 0 ]; then
+	read -r URL && readonly URL
+fi
+
+[ -n "${URL}" ] || err "${0##*/} needs a URL!"
+
+
 readonly DEPENDENCIES='dmenu
 ftp
 mpv
@@ -30,6 +40,12 @@ notify-send
 sxiv
 xclip
 yt-dlp'
+
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
+done
+
 
 readonly OPTIONS='copy duration
 copy title
@@ -42,22 +58,6 @@ read
 view image
 watch
 watch (loop)'
-
-
-if [ -n "$1" ]; then
-	readonly URL="$1"
-elif [ ! -t 0 ]; then
-	read -r URL && readonly URL
-fi
-
-[ -n "${URL}" ] || err "${0##*/} needs a URL!"
-
-
-echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" >/dev/null 2>&1 ||
-		err "${dependency} not found in PATH."
-done
-
 
 echo "${OPTIONS}" |
 	case "$(fzf)" in
