.local/bin/mpv: dependency on common.sh removed, PROGRAM_NAME var removed for now

diff --git a/.local/bin/mpv b/.local/bin/mpv
--- a/.local/bin/mpv
+++ b/.local/bin/mpv
@@ -25,31 +25,45 @@
 # also, disable xcompmgr(1) during playback since it seems to cause
 # screen tearing with modesetting(4)
 
-PROGRAM_NAME="${0##*/}"
 
-
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
-
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${PROGRAM_NAME} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
+}
 
-fi
+
+args_needed() {
+  unset ATLEAST
+
+  if [ "$1" = 'atleast' ]; then
+    ATLEAST=1
+    shift
+  fi
 
 
-check_grafix
+  case "$1" in
+
+    ''|*[!0-9]*)
+      err "args_needed() needs a number."
+
+      ;;
+
+  esac
+
+
+  if [ "${ATLEAST}" = 1 ]; then
+    err "At least $1 argument(s) required."
+
+  else
+    err "$1 argument(s) required."
+
+  fi
+}
 
 
 usage() {
   cat >&2 <<EOF
-${PROGRAM_NAME} [options] [media file]
+${0##*/} [options] [media file]
 
 See mpv(1) for more details.
 EOF
@@ -58,8 +72,9 @@ EOF
 }
 
 
-ARGS_NEEDED=1
-[ "$#" -ge "${ARGS_NEEDED}" ] || usage
+[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
+
+[ "$#" -ge 1 ] || args_needed atleast 1
 
 
 # TODO: maybe there is a way to do this so command -vp isn't issued
@@ -79,7 +94,7 @@ OS="$(uname)"
 [ "${OS}" = 'OpenBSD' ] && ulimit -c 0
 
 
-case "${PROGRAM_NAME}" in
+case "${0##*/}" in
 
   'mpv')
     [ "${OS}" = 'OpenBSD' ] && pkill xcompmgr >/dev/null 2>&1
@@ -99,7 +114,7 @@ case "${PROGRAM_NAME}" in
     ;;
 
   *)
-    err "${PROGRAM_NAME} is not an expected program name."
+    err "${0##*/} is not an expected program name."
 
     ;;
 
