.local/bin/mpv: restructure stuff into a case statement so that the differences between mpv and mpva are more apparent and are easier to edit.
.local/bin/mpva: deleted, because git does not track hard links and it
duplicates changes. since it is a workaround wrapper to begin with, I
can deal with making a hard link manually on the machine(s) that need
it

diff --git a/.local/bin/mpv b/.local/bin/mpv
--- a/.local/bin/mpv
+++ b/.local/bin/mpv
@@ -19,19 +19,28 @@ PROGRAM_NAME="${0##*/}"
 # ksh(1).
 #
 # shellcheck disable=SC3045
-if [ "${OS}" = 'OpenBSD' ]; then
-  ulimit -c 0
-  [ "${PROGRAM_NAME}" = 'mpv' ] && pkill xcompmgr
-fi
-
+[ "${OS}" = 'OpenBSD' ] && ulimit -c 0
 
 case "${PROGRAM_NAME}" in
-  'mpv')  "${MPV}" "$@"                                           ;;
-  'mpva') "${MPV}" --no-video "$@"                                ;;
-  *)      echo "${PROGRAM_NAME} is invalid, exiting." >&2; exit 1 ;;
+
+  'mpv')
+    [ "${OS}" = 'OpenBSD' ] && pkill xcompmgr
+
+    "${MPV}" "$@"
+
+    [ "${OS}" = 'OpenBSD' ] && xcompmgr &
+
+    ;;
+
+  'mpva')
+    "${MPV}" --no-video "$@"
+
+    ;;
+
+  *)
+    echo "${PROGRAM_NAME} is invalid, exiting." >&2
+    exit 1
+
+    ;;
+
 esac
-
-
-if [ "${OS}" = 'OpenBSD' ] && [ "${PROGRAM_NAME}" = 'mpv' ]; then
-  xcompmgr &
-fi
