remove emojis/unnecessary '--'/make heredoc more readable

diff --git a/.local/bin/nsc b/.local/bin/nsc
--- a/.local/bin/nsc
+++ b/.local/bin/nsc
@@ -17,10 +17,10 @@
 set -e
 
 
-if [ -x "$(command -v -- 'doas')" ]; then
+if [ -x "$(command -v 'doas')" ]; then
 	alias priv='doas '
 
-elif [ -x "$(command -v -- 'sudo')" ]; then
+elif [ -x "$(command -v 'sudo')" ]; then
 	alias priv='sudo '
 
 fi
@@ -55,7 +55,7 @@ fix_perms() {
 }
 
 
-[ -x "$(command -v -- 'nmap')" ] || err 'nmap not found in PATH or not executable.'
+[ -x "$(command -v 'nmap')" ] || err 'nmap not found in PATH or not executable.'
 [ -z "$1" ] && usage
 
 TMPDIR="$(mktemp -d)"
