style

diff --git a/.local/bin/nsc b/.local/bin/nsc
--- a/.local/bin/nsc
+++ b/.local/bin/nsc
@@ -15,9 +15,9 @@
 
 set -eu
 
-if command -v 'doas' >/dev/null 2>&1; then
+if command -v 'doas' > /dev/null 2>&1; then
 	alias priv='doas '
-elif command -v 'sudo' >/dev/null 2>&1; then
+elif command -v 'sudo' > /dev/null 2>&1; then
 	alias priv='sudo '
 fi
 
@@ -27,7 +27,7 @@ err() {
 }
 
 usage() {
-	cat >&2 <<EOF
+	cat >&2 << EOF
 usage:
 ${0##*/} [target] [options]
 EOF
@@ -39,20 +39,17 @@ nsc() {
 		-oA "${TMPDIR}/nmap-$(date '+%F')" "$@"
 }
 
-
-command -v 'priv' >/dev/null 2>&1 ||
+command -v 'priv' > /dev/null 2>&1 ||
 	err 'priv alias left undefined; no privilege elevation available.'
 
-command -v 'nmap' >/dev/null 2>&1 || err 'nmap not found in PATH.'
+command -v 'nmap' > /dev/null 2>&1 || err 'nmap not found in PATH.'
 
 [ -n "$*" ] || usage
-
 
 TMPDIR="$(mktemp -d)"
 readonly TMPDIR
 
 nsc "$@"
-
 
 readonly UNPRIV_USER="${LOGNAME}"
 priv chown -R -- "${UNPRIV_USER}:${UNPRIV_USER}" "${TMPDIR}"
@@ -60,6 +57,5 @@ priv chown -R -- "${UNPRIV_USER}:${UNPRIV_USER}" "${TMPDIR}"
 find "${TMPDIR}" \
 	\( -type f ! -perm 600 -exec chmod 600 '{}' \; \) -o \
 	\( -type d ! -perm 700 -exec chmod 700 '{}' \; \)
-
 
 echo "Scan finished, results available in ${TMPDIR}."
diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -21,7 +21,7 @@ err() {
 }
 
 usage() {
-	cat >&2 <<EOF
+	cat >&2 << EOF
 usage:
 ${0##*/} [cue file] [FLAC file]
 
@@ -73,7 +73,6 @@ splitflac() {
 	"${CUETAG}" "$1" ./*.flac || err 'Unable to tag FLAC files.'
 }
 
-
 while getopts cd opt; do
 	case "${opt}" in
 		c) readonly CONVERT='yes' ;;
@@ -88,33 +87,29 @@ shift $((OPTIND - 1))
 
 set -u
 
-
 # cuetag is checked later since the executable's name isn't consistent
 # among operating systems.
 readonly DEPENDENCIES='flac
 shntool'
 
 echo "${DEPENDENCIES}" | while read -r dependency; do
-	command -v -- "${dependency}" >/dev/null 2>&1 ||
+	command -v -- "${dependency}" > /dev/null 2>&1 ||
 		err "${dependency} not found in PATH."
 done
 
-
-if command -v 'cuetag' >/dev/null 2>&1; then
+if command -v 'cuetag' > /dev/null 2>&1; then
 	readonly CUETAG='cuetag'
-elif command -v 'cuetag.sh' >/dev/null 2>&1; then
+elif command -v 'cuetag.sh' > /dev/null 2>&1; then
 	readonly CUETAG='cuetag.sh'
 fi
 
 [ -n "${CUETAG}" ] || err 'Neither cuetag nor cuetag.sh found.'
 
-
 [ "${CONVERT}" = 'yes' ] && {
 	# makes sense to check dependency only when it's really needed
-	command -v 'sox' >/dev/null 2>&1 || err 'sox not found in PATH.'
+	command -v 'sox' > /dev/null 2>&1 || err 'sox not found in PATH.'
 	convert_to_16bit "$2"
 }
-
 
 # Check for sector boundary errors and fix them if they are present
 # before splitting the FLAC file.
@@ -123,13 +118,11 @@ shnfix -c -- "$2" && {
 	mv -- "${2%.flac}-fixed.flac" "$2"
 }
 
-
 CRLESS_CUESHEET="$(mktemp)"
 readonly CRLESS_CUESHEET
 
 # removes carriage returns from cuesheet
 tr -d '\r' < "$1" > "${CRLESS_CUESHEET}"
 mv "${CRLESS_CUESHEET}" "$1"
-
 
 splitflac "$1" "$2"
diff --git a/.local/bin/sysinfo b/.local/bin/sysinfo
--- a/.local/bin/sysinfo
+++ b/.local/bin/sysinfo
@@ -44,7 +44,6 @@ get_battery_life() {
 			;;
 	esac
 
-
 	minutes=$((estimated_battery_life % 60))
 	hours=$((estimated_battery_life / 60))
 	remaining="~${hours}h & ${minutes}m"
@@ -54,7 +53,7 @@ get_battery_life() {
 
 show_battery_life() {
 	case "${BATTERY_STATUS}" in
-		4|255)
+		4 | 255)
 			warn 'Battery status: absent/unknown.'
 			return 1
 			;;
@@ -71,10 +70,12 @@ show_battery_life() {
 		1) echo "chr: at ${percentage}%" ;;
 
 		# No battery information to display.
-		*) warn 'No battery information.'; return 1 ;;
+		*)
+			warn 'No battery information.'
+			return 1
+			;;
 	esac
 }
-
 
 show_temperature() {
 	temperature="$(sysctl -n hw.sensors.cpu0.temp0)"
@@ -102,17 +103,14 @@ sysinfo() {
 +|C +@fn=1; $(show_current_track) +|R +@fn=0; $(show_disk_space)"
 }
 
-
 [ "$(uname)" = 'OpenBSD' ] || err "${PROGRAM_NAME} only supports OpenBSD."
-command -v 'mpc' >/dev/null 2>&1 || err 'mpc not found in PATH.'
-
+command -v 'mpc' > /dev/null 2>&1 || err 'mpc not found in PATH.'
 
 BATTERY_STATUS="$(apm -b)"
 readonly BATTERY_STATUS
 
 HOSTNAME="$(hostname -s)"
 readonly HOSTNAME
-
 
 while true; do
 	sysinfo
