might as well just use shnsplit here

diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -86,9 +86,7 @@ splitflac() {
 	# spaces in shnsplit filename messes up cue tagging, so just leave
 	# the default in place. it's the only way to be sure that we won't run
 	# into that issue, because %t will often add spaces too.
-	if ! cuebreakpoints -- "$1" | shnsplit -o flac -- "$2"; then
-		err 'Unable to split the FLAC file.'
-	fi
+	shnsplit -f "$1" -o flac -- "$2" || err 'Unable to split the FLAC file.'
 
 	[ "${DELETE}" = 'yes' ] && rm -- "$2"
 	[ -e "$2" ] && mv -- "$2" "$2.bak"
