.local/bin/splitflac: dependency on common.sh removed

diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -16,26 +16,15 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
-
-fi
+}
 
 
 usage() {
   cat >&2 <<EOF
-${0##*/} requires ${args_needed} argument(s).
-
 usage:
 ${0##*/} [cue file] [FLAC file]
 
@@ -44,6 +33,35 @@ ${0##*/} [cue file] [FLAC file]
 EOF
 
   exit 1
+}
+
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
+}
+
+
+args_needed() {
+  case "$1" in
+
+    ''|*[!0-9]*)
+      err "args_needed() needs a number."
+
+      ;;
+
+  esac
+
+  err "$1 argument(s) required."
 }
 
 
@@ -109,8 +127,6 @@ shnfix
 shnsplit
 EOF
 
-readonly args_needed=2
-
 while getopts cd opt; do
 
   case "${opt}" in
@@ -123,7 +139,7 @@ done
 
 shift $((OPTIND - 1))
 
-[ "$#" = "${args_needed}" ] || usage
+[ "$#" = 2 ] || args_needed 2
 
 assign_cuetag
 
