clean up

diff --git a/.local/bin/splitflac b/.local/bin/splitflac
--- a/.local/bin/splitflac
+++ b/.local/bin/splitflac
@@ -15,130 +15,119 @@
 
 set -e
 
-
 err() {
 	printf '%s\n' "$*" >&2
 	exit 1
 }
 
-
 usage() {
-	err "usage:
+	cat >&2 <<EOF
+usage:
 ${0##*/} [cue file] [FLAC file]
 
 -c : convert 24bit flac to 16bit before splitting (sox needed)
--d : delete the original FLAC file."
+-d : delete the original FLAC file.
+EOF
+	exit 1
 }
-
-
-check_deps() {
-	while read -r dependency; do
-
-		[ -x "$(command -v -- "${dependency}")" ] \
-			|| err "${dependency} not found in PATH or not executable."
-
-	done
-}
-
-
-# determines which executable name to use for cuetag.
-assign_cuetag() {
-	if [ -x "$(command -v 'cuetag')" ]; then
-		readonly CUETAG='cuetag'
-
-	elif [ -x "$(command -v 'cuetag.sh')" ]; then
-		readonly CUETAG='cuetag.sh'
-
-	else
-		err 'Neither cuetag nor cuetag.sh found.'
-
-	fi
-}
-
 
 # converts a 24-bit FLAC file to a 16-bit FLAC file with sox(1).
 #
 # $1 is a FLAC file to be converted.
-conv16() {
+convert_to_16bit() {
 	STAGING_FILE="${1%.flac}-staging.flac"
 	readonly STAGING_FILE
 
 	# http://sox.sourceforge.net/Docs/FAQ
 	#
-	# according to sox(1), most noise shaping filters are only available
+	# According to sox(1), most noise shaping filters are only available
 	# at 44.1kHz, so that is the chosen sample rate.
 	if sox -SG "$1" -b 16 "${STAGING_FILE}" rate -v 44100 dither -s; then
-		[ "${DELETE}" = 'yes' ] && rm -- "$1"
-		[ -e "$1" ] && mv -- "$1" "$1-24bit.bak"
+
+		if [ "${DELETE}" = 'yes' ]; then
+			rm -- "$1"
+		else
+			mv -- "$1" "$1-24bit.bak"
+		fi
 
 		mv -- "${STAGING_FILE}" "$1"
-
 	else
 		err 'Failed to convert 24-bit FLAC file to 16-bit.'
-
 	fi
 }
-
 
 splitflac() {
 	[ -e "$2.bak" ] && err "$2.bak exists, exiting to prevent clobbering."
 
-	# spaces in shnsplit filename messes up cue tagging, so just leave
-	# the default in place. it's the only way to be sure that we won't run
-	# into that issue, because %t will often add spaces too.
+	# Spaces in shnsplit filename messes up cue tagging, so just leave
+	# the default in place. It's the only way to be sure that we won't
+	# run into that issue (%t often contains spaces).
 	shnsplit -f "$1" -o flac -- "$2" || err 'Unable to split the FLAC file.'
 
-	[ "${DELETE}" = 'yes' ] && rm -- "$2"
-	[ -e "$2" ] && mv -- "$2" "$2.bak"
+	if [ "${DELETE}" = 'yes' ]; then
+		rm -- "$2"
+	else
+		mv -- "$2" "$2.bak"
+	fi
 
 	"${CUETAG}" "$1" ./*.flac || err 'Unable to tag FLAC files.'
 }
 
 
-# cuetag is checked in assign_cuetag() rather than check_deps() since
-# the executable's name isn't consistent among operating systems.
-check_deps <<-'EOF'
-	cuebreakpoints
-	flac
-	shnfix
-	shnsplit
-EOF
-
 while getopts cd opt; do
-
 	case "${opt}" in
 		c) readonly CONVERT='yes' ;;
 		d) readonly DELETE='yes' ;;
 		*) usage ;;
 	esac
-
 done
-
 shift $((OPTIND - 1))
 
-[ -z "$1" ] && usage
-[ -z "$2" ] && usage
+[ -n "$1" ] || usage
+[ -n "$2" ] || usage
 
-assign_cuetag
+
+# cuetag is checked later since the executable's name isn't consistent
+# among operating systems.
+readonly DEPENDENCIES='flac
+shntool'
+
+echo "${DEPENDENCIES}" | while read -r dependency; do
+	command -v -- "${dependency}" >/dev/null 2>&1 ||
+		err "${dependency} not found in PATH."
+done
+
+
+if command -v 'cuetag' >/dev/null 2>&1; then
+	readonly CUETAG='cuetag'
+elif command -v 'cuetag.sh' >/dev/null 2>&1; then
+	readonly CUETAG='cuetag.sh'
+else
+	err 'Neither cuetag nor cuetag.sh found.'
+fi
+
 
 [ "${CONVERT}" = 'yes' ] && {
 	# makes sense to check dependency only when it's really needed
-	echo 'sox' | check_deps
-	conv16 "$2"
+	command -v 'sox' >/dev/null 2>&1 || err 'sox not found in PATH.'
+	convert_to_16bit "$2"
 }
 
-# checks for sector boundary errors and fixes them if they are present
+
+# Check for sector boundary errors and fix them if they are present
 # before splitting the FLAC file.
 shnfix -c -- "$2" && {
 	shnfix -o flac -- "$2"
 	mv -- "${2%.flac}-fixed.flac" "$2"
 }
 
+
 CRLESS_CUESHEET="$(mktemp)"
 readonly CRLESS_CUESHEET
 
 # removes carriage returns from cuesheet
-tr -d '\r' <"$1" >"${CRLESS_CUESHEET}"
+tr -d '\r' < "$1" > "${CRLESS_CUESHEET}"
 mv "${CRLESS_CUESHEET}" "$1"
+
 
 splitflac "$1" "$2"
