sysinfo: while loop now in main()

diff --git a/.local/bin/sysinfo b/.local/bin/sysinfo
--- a/.local/bin/sysinfo
+++ b/.local/bin/sysinfo
@@ -100,32 +100,32 @@ show_cpu_freq() {
 # TODO: change so that sysinfo() will only print track if MPD is currently
 # playing music
 sysinfo() {
-  while true; do
-    pgrep -q mpd
-    case "$?" in
-      0)
+  pgrep -q mpd
+  case "$?" in
+    0)
 # spaces bork ${stats}
 stats="${bgfg} %{l}$(show_battery)$(show_temp)\
 %{c}$(show_track) %{r}$(show_volume)$(show_disk_space)\
 $(show_date)"
-        printf "%s" "${stats}"
-        ;;
-      1)
+      printf "%s" "${stats}"
+      ;;
+    1)
 stats="${bgfg} %{l}$(show_battery)$(show_temp)\
 %{r}$(show_volume)$(show_disk_space)\
 $(show_date)"
-        printf "%s" "${stats}"
-        ;;
-    esac
-    sleep 5
-  done
+      printf "%s" "${stats}"
+      ;;
+  esac
 }
 
 main() {
   import_colors || err "Unable to import colors."
   delimiter="  %{F${color3}}|%{F${foreground}}  "
   bgfg="%{B${background}} %{F${foreground}"
-  sysinfo || err "sysinfo() failed."
+  while true; do
+    sysinfo || err "sysinfo() failed"
+    sleep 5
+  done
 }
 
 main
