avoids attempting to print MPD info if the daemon isn't enabled

diff --git a/.local/bin/sysinfo b/.local/bin/sysinfo
--- a/.local/bin/sysinfo
+++ b/.local/bin/sysinfo
@@ -97,15 +97,20 @@ show_cpu_freq() {
   sec_print "cpu: ${formatted_cpu_freq} GHz"
 }
 
-sysinfo() {
-  while true; do
-  # indenting here affects spacing in the bar
+main() {
+  if rcctl ls on | grep -E "^mpd$"; then
 stats="${bgfg} %{l}$(show_battery)$(show_temp)\
 %{c}$(show_track) %{r}$(show_volume)$(show_disk_space)\
 $(show_date)"
-    sec_print "${stats}"
+  else
+stats="${bgfg} %{l}$(show_battery)$(show_temp)\
+%{r}$(show_volume)$(show_disk_space)\
+$(show_date)"
+  fi
+  while true; do
+    sec_print "${stats}" || err "Unable to print statistics."
     sleep 5
   done
 }
 
-sysinfo || err "Something went wrong with sysinfo."
+main
