viewimg: removes dependency on common.sh

diff --git a/.local/bin/viewimg b/.local/bin/viewimg
--- a/.local/bin/viewimg
+++ b/.local/bin/viewimg
@@ -16,31 +16,35 @@
 
 set -e
 
-readonly LIBRARY="${HOME}/.local/bin/common.sh"
 
-if [ -r "${LIBRARY}" ]; then
-  . "${LIBRARY}"
-
-else
-  cat >&2 <<EOF
-${LIBRARY} doesn't exist or isn't readable.
-${0##*/} may not function correctly without it.
-EOF
-
+err() {
+  printf '%s\n' "$*" >&2
   exit 1
-
-fi
+}
 
 
 usage() {
   cat >&2 <<EOF
-${0##*/} requires ${args_needed} argument(s).
-
 usage:
 ${0##*/} [URL]
 EOF
 
   exit 1
+}
+
+
+check_deps() {
+  while read -r dependency; do
+
+    if [ -x "$(command -v -- "${dependency}")" ]; then
+      continue
+
+    else
+      err "${dependency} not found in PATH or not executable."
+
+    fi
+
+  done
 }
 
 
@@ -54,20 +58,15 @@ viewimg() {
 }
 
 
-prereqs() {
-  check_grafix
+[ -z "${DISPLAY}" ] && err "${0##*/} requires a graphical environment."
 
-  check_deps <<'EOF'
+check_deps <<'EOF'
 ftp
 sxiv
 EOF
 
-  readonly args_needed=1
-  [ "$#" = "${args_needed}" ] || usage
-}
+[ -z "$1" ] && usage
 
-
-prereqs "$@"
 
 viewimg "$1" >/dev/null 2>&1
 
