ksh-aliases: minor style

diff --git a/.config/ksh/aliases b/.config/ksh/aliases
--- a/.config/ksh/aliases
+++ b/.config/ksh/aliases
@@ -3,7 +3,7 @@
 # TODO: add complain_missing() to other areas that aren't OS specific,
 # as those should be handled in the case statement in main()
 complain_missing() {
-  echo >&2 "[$(date '+%F %H:%M:%S')]: $1 not found, so related aliases disabled."
+  echo "[$(date '+%F %H:%M:%S')]: $1 not found, so related aliases disabled." >&2
   return 1
 }
 
